Longhorn v1.1.0 master
rancher/charts pull request #1143
Opened 2021-04-23 05:34 UTC by cclhsu

Longhorn v1.1.0 master

Signed-off-by: Clark Hsu <clark.hsu@suse.com>

2021-04-23 05:40 UTC, shuo-wu requested changes
1. It's better to split into 2 commits:
    1. Copy `latest` to `v1.1.0`
    2. Update `latest` with v1.1.1 Chart
2.  The directory name is wrong.

2021-04-23 06:06 UTC, shuo-wu commented
The commit title doesn't match the actual content.

2021-04-23 06:06 UTC, jenting requested changes

2021-04-23 06:06 UTC, jenting commented on charts/longhorn/v1.1.0/Chart.yaml
> +appVersion: v1.1.1
It should copy directly from the `lastest` folder (which is v1.1.0)

2021-04-23 06:09 UTC, shuo-wu commented
@cbron Hi, can you tell us what we need to do for the ci failure? I haven't seen this check previously.

2021-04-23 06:11 UTC, jenting commented
> @cbron Hi, can you tell us what we need to do for the ci failure? I haven't seen this check previously.

The root cause is helm2 deprecated the URL https://kubernetes-charts.storage.googleapis.com.
The only way to fix is to use helm v2.17.0 in the CI test.

2021-04-23 06:29 UTC, jenting approved these changes

2021-04-23 09:01 UTC, shuo-wu commented
The 1st commit is like renaming `latest` to `v1.1.0`

2021-04-26 02:34 UTC, shuo-wu commented
> The 1st commit is like renaming `latest` to `v1.1.0`

^^ @cclhsu Check this comment

2021-04-26 02:58 UTC, jenting submitted a review, later dismissed

2021-04-26 04:12 UTC, shuo-wu submitted a review, later dismissed

2021-04-27 03:33 UTC, cclhsu commented
@cbron @PennyScissors Can you help review this PR.  We would like to have the Longhorn Chart v1.1.1 release since Longhorn v1.1.1 is already released.  Thanks!

2021-04-27 16:17 UTC, innobead commented
cc @khushboo-rancher

2021-04-27 16:48 UTC, PennyScissors commented
The CI is currently broken due to a custom image that hasn't been updated, but you can do the following to test the chart yourself locally.

1. Add rancher-charts remote to your fork and fetch master
`git remote add -ft master rancher-charts https://github.com/rancher/charts.git`

2. Run ct lint
```
docker run -v $(pwd):/rancher-charts -w /rancher-charts quay.io/helmpack/chart-testing:latest ct lint \
--remote rancher-charts \
--target-branch master \
--validate-maintainers=false \
--chart-dirs charts/<chart-dir-name>
```

2021-04-27 17:54 UTC, cclhsu commented
> The CI is currently broken due to a custom image that hasn't been updated, but you can do the following to test the chart yourself locally using the latest image.
> 
> 1. Add rancher-charts remote to your fork and fetch master
>    `git remote add -ft master rancher-charts https://github.com/rancher/charts.git`
> 2. Run ct lint
> 
> ```
> docker run -v $(pwd):/rancher-charts -w /rancher-charts quay.io/helmpack/chart-testing:latest ct lint \
> --remote rancher-charts \
> --target-branch master \
> --validate-maintainers=false \
> --chart-dirs charts/<chart-dir-name>
> ```

LINT pass against the PR branch.
```
cclhsu@dell-linux-nb:~/src/github.com/cclhsu_rancher/charts> REMOTE=rancher_charts
cclhsu@dell-linux-nb:~/src/github.com/cclhsu_rancher/charts> BRANCH=Longhorn_v1.1.0_master # master
cclhsu@dell-linux-nb:~/src/github.com/cclhsu_rancher/charts> CHART=longhorn
cclhsu@dell-linux-nb:~/src/github.com/cclhsu_rancher/charts> cd ~/src/github.com/cclhsu_rancher/charts
cclhsu@dell-linux-nb:~/src/github.com/cclhsu_rancher/charts> docker run -v $(pwd):/rancher-charts -w /rancher-charts quay.io/helmpack/chart-testing:latest ct lint \
> --target-branch ${BRANCH} \
> --validate-maintainers=false \
> --chart-dirs charts/${CHART}
Linting charts...
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

2021-04-27 18:17 UTC, khushboo-rancher commented
Validated the changes with Rancher cluster manager app. The chart looks good.

2021-04-27 18:17 UTC, PennyScissors commented
@cclhsu Looks like the path to --chart-dirs might be incorrect and it couldn't find any charts. The output should look like this.
```
docker run -v $(pwd):/rancher-charts -w /rancher-charts quay.io/helmpack/chart-testing:latest ct lint \
--remote rancher-charts \
--target-branch master \
--validate-maintainers=false \
--chart-dirs charts/longhorn  
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 longhorn => (version: "1.1.1", path: "charts/longhorn/latest")
 longhorn => (version: "1.1.0", path: "charts/longhorn/v1.1.0")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'longhorn => (version: "1.1.1", path: "charts/longhorn/latest")'
Checking chart 'longhorn => (version: "1.1.1", path: "charts/longhorn/latest")' for a version bump...
Old chart version: 1.1.0
New chart version: 1.1.1
Chart version ok.
Validating /rancher-charts/charts/longhorn/latest/Chart.yaml...
Validation success! 👍
charts/longhorn/latest/Chart.yaml
  28:113    error    no new line character at the end of file  (new-line-at-end-of-file)

Linting chart 'longhorn => (version: "1.1.0", path: "charts/longhorn/v1.1.0")'
Checking chart 'longhorn => (version: "1.1.0", path: "charts/longhorn/v1.1.0")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-charts/charts/longhorn/v1.1.0/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/v1.1.0

1 chart(s) linted, 0 chart(s) failed
Error: Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ longhorn => (version: "1.1.1", path: "charts/longhorn/latest") > Error waiting for process: exit status 1
 ✔︎ longhorn => (version: "1.1.0", path: "charts/longhorn/v1.1.0")
------------------------------------------------------------------------------------------------------------------------
Error linting charts: Error processing charts
```

2021-04-27 18:22 UTC, meldafrawi commented
LGTM

2021-04-27 18:38 UTC, cclhsu commented
Fixed the end-of-line error
1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ longhorn => (version: "1.1.1", path: "charts/longhorn/latest")
 ✔︎ longhorn => (version: "1.1.0", path: "charts/longhorn/v1.1.0")
------------------------------------------------------------------------------------------------------------------------

2021-04-27 19:08 UTC, PennyScissors approved these changes

2021-04-28 17:09 UTC, cclhsu commented
@cbron Please help review the PR.

2021-04-28 23:33 UTC, cbron approved these changes
I just skimmed, most changes are functional so I trust that they are right and QA has already validated. Once we merge this it will go live to production clusters so we must be sure it is good. So I will leave it to longhorn team to merge.

2021-04-29 03:54 UTC, innobead commented
> I just skimmed, most changes are functional so I trust that they are right and QA has already validated. Once we merge this it will go live to production clusters so we must be sure it is good. So I will leave it to longhorn team to merge.

I don't have permission to do that, so probably need @yasker help on that.

2021-04-29 05:36 UTC, merged

2021-04-29 05:37 UTC, yasker commented
Merged. Thanks @cbron @PennyScissors .