bump rancher-backup to 1.1.2-rc1
rancher/charts pull request #1273
Opened 2021-06-15 00:17 UTC by jiaqiluo

2021-06-16 03:13 UTC, nickgerace approved these changes

2021-06-17 00:36 UTC, aiyengar2 requested changes
@jiaqiluo we need to drop the 100.0.0+up1.1.1 in favor of this right?

2021-06-17 04:10 UTC, jiaqiluo commented
@aiyengar2  Good point! 100.0.0+up1.1.1 is deleted.

2021-06-17 17:02 UTC, aiyengar2 approved these changes

2021-06-17 17:03 UTC, merged