Forward port release-v2.5 branch
rancher/charts pull request #1364
Opened 2021-07-16 20:24 UTC by brendarearden

Due to OOB releases, the release-v2.5 branch and the release-v2.6 branch were out of synch. This pr has the most recent changes from release-v2.5 in it. 

Steps used:
1. `git fetch upstream`
2. `git checkout -b forward-port-releases upstream/release-v2.5`
3. `git pull upstream release-v2.6 --rebase
4. Resolved index.yaml merge conflicts by deleting the index.yaml, running `helm repo index --url assets assets`, moving the resulting index.yaml to the top level directory to replace the deleted one, `git add .` and then `git rebase --continue`
5. After --rebase was completed, deleted the index.yaml and regenerated it by running `helm repo index --url assets assets`, moving the resulting index.yaml to the top level directory to replace the deleted one, `git add .` and then pushed upstream for PR.

2021-07-16 20:33 UTC, jiaqiluo requested changes
Can you remove the directory `packages/rancher-kiali-server` ?

2021-07-16 20:44 UTC, jiaqiluo approved these changes
LGMT

2021-07-16 20:44 UTC, jiaqiluo commented on index.yaml
> +    version: 1.9.600
new entry 1/2

2021-07-16 20:44 UTC, jiaqiluo commented on index.yaml
> +    version: 0.1.100+up0.1.1
new entry 2/2

2021-07-19 23:32 UTC, brendarearden commented
closing this PR in favor of https://github.com/rancher/charts/pull/1367

2021-07-19 23:32 UTC, closed without merging