Fix/issue 33472
rancher/charts pull request #1411
Opened 2021-08-13 02:09 UTC by paynejacob

https://github.com/rancher/rancher/issues/33472

we were not apply the klog parser to kubelet logs

2021-08-13 16:27 UTC, nickgerace submitted a review, later dismissed

2021-08-13 22:47 UTC, cbron requested changes
Needs new asset and index.yaml regenerate

2021-08-14 00:06 UTC, paynejacob commented
@cbron not sure why it didn't work the first time

2021-08-16 23:15 UTC, cbron approved these changes
No version change so no deletion or index update. lgtm

2021-08-16 23:18 UTC, merged