Fix/issue 34244
rancher/charts pull request #1421
Opened 2021-08-19 23:29 UTC by paynejacob

updated aks operator to v1.0.1

2021-08-19 23:32 UTC, snasovich approved these changes

2021-08-20 17:39 UTC, cbron requested changes

2021-08-20 17:39 UTC, cbron commented on charts/rancher-aks-operator/rancher-aks-operator/100.0.0+up1.0.1/Chart.yaml
> +annotations:
Since this is the final release we need to remove the rc asset from assets and from index.yaml

2021-08-20 22:24 UTC, cbron approved these changes
lgtm now, but wait for one of the kev2 devs to approve

2021-08-20 23:37 UTC, thedadams approved these changes

2021-08-23 15:53 UTC, cmurphy approved these changes

2021-08-23 15:54 UTC, merged