[WIP] Update gatekeeper to 3.6.0
rancher/charts pull request #1463
Opened 2021-09-03 12:09 UTC by rayandas

https://github.com/rancher/rancher/issues/34593

2021-09-08 23:05 UTC, aiyengar2 requested changes
nit: for our git history, can you name the first commit "Update gatekeeper to 3.6.0" and the second commit "make charts"?

Other than that LGTM

2021-09-09 10:32 UTC, rayandas commented
@aiyengar2 changed the commit messages as suggested.

2021-09-13 17:41 UTC, aiyengar2 approved these changes
LGTM

2021-09-13 21:01 UTC, cmurphy approved these changes

2021-09-13 23:28 UTC, merged