Add instructions to separate multiple images inside values.yaml
rancher/charts pull request #1508
Opened 2021-09-28 10:41 UTC by rayandas

This PR adds an instruction about how/when to separate images inside `packages/<package-name>/charts/values.yaml` after running `make prepare`.

2021-09-28 17:47 UTC, nickgerace approved these changes
Awesome! Thank you

2021-10-01 05:32 UTC, rayandas commented
cc: @PennyScissors

2021-10-07 18:46 UTC, aiyengar2 requested changes
@rayandas we can't modify this README.md today since it is currently managed by `make template`, as the source of these docs exist in upstream here: https://github.com/rancher/charts-build-scripts/tree/579e62f8a7bc7aebf61905efe7f674e0c6e9a382/templates/template.

However, I am working https://github.com/rancher/charts-build-scripts/issues/60, which will modify these docs anyways, so I can put the fix to the docs in in that PR.

2021-11-12 05:33 UTC, rayandas commented
Closing this as it's WIP in https://github.com/rancher/charts-build-scripts/issues/62

2021-11-12 05:33 UTC, closed without merging