Add longhorn 1.2.2 chart dev 2.6
rancher/charts pull request #1537
Opened 2021-10-07 12:27 UTC by innobead

Signed-off-by: David Ko <dko@suse.com>

As discussed with @cbron , we would like to replace 1.2.0 with 1.2.2 in the coming 2.6.1.

2021-10-07 15:32 UTC, jiaqiluo submitted a review, later dismissed
LGTM

2021-10-07 16:00 UTC, aiyengar2 requested changes
Version should remain 100.1.0 since Rancher has never released a 100.1.0 before.

2021-10-07 18:04 UTC, innobead commented on packages/longhorn-1.2/package.yaml
> +version: 100.1.2
I can change it but I thought it will be good to use the patch version part to match the upstream chart? WDYT?

cc @cbron @jiaqiluo

2021-10-07 18:17 UTC, jiaqiluo commented on packages/longhorn-1.2/package.yaml
> +version: 100.1.2
Good catch. I forgot that 100.1.0 is also not released.

2021-10-07 18:21 UTC, innobead commented on packages/longhorn-1.2/package.yaml
> +version: 100.1.2
Thank you guys 👍

2021-10-07 22:12 UTC, cbron reviewed
lgtm, needs images mirrored first

2021-10-08 00:04 UTC, meldafrawi commented
Validated Longhorn installation/upgrade rancher 2.6: **LGTM**

2021-10-08 15:41 UTC, merged