[dev-v2.6] Refactor/add CPI and CSI charts
rancher/charts pull request #1602
Opened 2021-11-09 00:25 UTC by PennyScissors

Refactors the names of the following charts:
CPI 100.0.1 to 100.1.0+up1.0.100
CSI 100.0.1 to 100.1.0+up2.3.0

In the case of CPI, the `appVersion` was reverted to match the `version` since having `1.21.0` was not correct.

2021-11-09 21:16 UTC, jiaqiluo approved these changes
LGTM

2021-11-09 23:58 UTC, jiaqiluo requested changes

2021-11-09 23:58 UTC, jiaqiluo commented on charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0+up1.0.100/Chart.yaml
> +  catalog.cattle.io/rancher-version: '>= 2.6.0-0'
```suggestion
  catalog.cattle.io/rancher-version: '>= 2.6.0-0 <= 2.6.99-0'
```

2021-11-10 00:24 UTC, jiaqiluo approved these changes

2021-11-10 19:04 UTC, aiyengar2 approved these changes
LGTM

2021-11-10 19:24 UTC, merged