[dev-v2.6-vsphere-release] Forwardport CPI 1.0.1 and update CSI 100.0.1+up2.1.1 kubeVersion
rancher/charts pull request #1617
Opened 2021-11-16 23:57 UTC by PennyScissors

2021-11-17 00:56 UTC, jiaqiluo requested changes
Comparing with the changes in this PR https://github.com/rancher/charts/pull/1613
- 
- CPI 1.0.000 shows in 2.6.0 (`catalog.cattle.io/rancher-version: < 2.6.1-0`), but will be hidden in 2.5.x 
- CSI 2.1.1's kubeVersion is changed in 2.5 but not here 
- CSI 2.1.000 shows in 2.6.0 (`catalog.cattle.io/rancher-version: < 2.6.1-0`), but will be hidden in 2.5.x

2021-11-17 23:16 UTC, aiyengar2 submitted a review, later dismissed
Ran the following commands to check whether this PR is good to go:

```
git fetch upstream
git fetch steven

mv assets 2.6-assets
git checkout upstream/dev-v2.5-vsphere-release -- assets
mv assets 2.5-assets

mkdir -p cpi/dev-v2.5/1.0.000
tar xvzf 2.5-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.000.tgz -C cpi/dev-v2.5/1.0.000 --strip-components=1
mkdir -p cpi/dev-v2.5/1.0.1
tar xvzf 2.5-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.1.tgz -C cpi/dev-v2.5/1.0.1 --strip-components=1
mkdir -p cpi/dev-v2.5/1.0.100
tar xvzf 2.5-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.100.tgz -C cpi/dev-v2.5/1.0.100 --strip-components=1

mkdir -p cpi/dev-v2.6/1.0.000
tar xvzf 2.6-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.000.tgz -C cpi/dev-v2.6/1.0.000 --strip-components=1
mkdir -p cpi/dev-v2.6/1.0.1
tar xvzf 2.6-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.1.tgz -C cpi/dev-v2.6/1.0.1 --strip-components=1
mkdir -p cpi/dev-v2.6/1.0.100
tar xvzf 2.6-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.100.tgz -C cpi/dev-v2.6/1.0.100 --strip-components=1
mkdir -p cpi/dev-v2.6/100.0.0
tar xvzf 2.6-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-100.0.0.tgz -C cpi/dev-v2.6/100.0.0 --strip-components=1
mkdir -p cpi/dev-v2.6/100.1.0+up1.0.100
tar xvzf 2.6-assets/rancher-vsphere-cpi/rancher-vsphere-cpi-100.1.0+up1.0.100.tgz -C cpi/dev-v2.6/100.1.0+up1.0.100 --strip-components=1

mkdir -p csi/dev-v2.5/2.1.000
tar xvzf 2.5-assets/rancher-vsphere-csi/rancher-vsphere-csi-2.1.000.tgz -C csi/dev-v2.5/2.1.000 --strip-components=1
mkdir -p csi/dev-v2.5/2.1.1
tar xvzf 2.5-assets/rancher-vsphere-csi/rancher-vsphere-csi-2.1.1.tgz -C csi/dev-v2.5/2.1.1 --strip-components=1
mkdir -p csi/dev-v2.5/2.3.0
tar xvzf 2.5-assets/rancher-vsphere-csi/rancher-vsphere-csi-2.3.0.tgz -C csi/dev-v2.5/2.3.0 --strip-components=1

mkdir -p csi/dev-v2.6/2.1.000
tar xvzf 2.6-assets/rancher-vsphere-csi/rancher-vsphere-csi-2.1.000.tgz -C csi/dev-v2.6/2.1.000 --strip-components=1
mkdir -p csi/dev-v2.6/2.1.1
tar xvzf 2.6-assets/rancher-vsphere-csi/rancher-vsphere-csi-2.1.1.tgz -C csi/dev-v2.6/2.1.1 --strip-components=1
mkdir -p csi/dev-v2.6/2.3.0
tar xvzf 2.6-assets/rancher-vsphere-csi/rancher-vsphere-csi-2.3.0.tgz -C csi/dev-v2.6/2.3.0 --strip-components=1
mkdir -p csi/dev-v2.6/100.0.0
tar xvzf 2.6-assets/rancher-vsphere-csi/rancher-vsphere-csi-100.0.0.tgz -C csi/dev-v2.6/100.0.0 --strip-components=1
mkdir -p csi/dev-v2.6/100.0.1+up2.1.1
tar xvzf 2.6-assets/rancher-vsphere-csi/rancher-vsphere-csi-100.0.1+up2.1.1.tgz -C csi/dev-v2.6/100.0.1+up2.1.1 --strip-components=1
mkdir -p csi/dev-v2.6/100.1.0+up2.3.0
tar xvzf 2.6-assets/rancher-vsphere-csi/rancher-vsphere-csi-100.1.0+up2.3.0.tgz -C csi/dev-v2.6/100.1.0+up2.3.0 --strip-components=1

# Expect no changes

diff -uNr cpi/dev-v2.5/1.0.000 cpi/dev-v2.6/1.0.000

diff -uNr cpi/dev-v2.5/1.0.1 cpi/dev-v2.6/1.0.1

diff -uNr cpi/dev-v2.5/1.0.100 cpi/dev-v2.6/1.0.100
# FAIL: support matrix removed

# Expect chart to have rancher version < 2.6

yq e '.annotations' cpi/dev-v2.6/100.0.0/Chart.yaml

# Expect different version and rancher-version annotations only

diff -uNr cpi/dev-v2.6/1.0.100 cpi/dev-v2.6/100.1.0+up1.0.100

# Check index.yaml

yq e '.entries.rancher-vsphere-cpi[] | {.version: {"annotations": .annotations, "kubeVersion": .kubeVersion}}' index.yaml

# Expect no changes

diff -uNr csi/dev-v2.5/2.1.000 csi/dev-v2.6/2.1.000

diff -uNr csi/dev-v2.5/2.1.1 csi/dev-v2.6/2.1.1

diff -uNr csi/dev-v2.5/2.3.0 csi/dev-v2.6/2.3.0
# FAIL: support matrix removed

# Expect chart to be hidden

yq e '.annotations' csi/dev-v2.6/100.0.0/Chart.yaml

# Expect different version and annotations only

diff -uNr csi/dev-v2.6/2.1.1 csi/dev-v2.6/100.0.1+up2.1.1
# FAIL: support matrix removed

diff -uNr csi/dev-v2.6/2.3.0 csi/dev-v2.6/100.1.0+up2.3.0

# Check index.yaml

yq e '.entries.rancher-vsphere-csi[] | {.version: {"annotations": .annotations, "kubeVersion": .kubeVersion}}' index.yaml
```

Did not inspect the contents of charts compared to assets and see that the support matrix is not included in some of the charts, but @PennyScissors and I talked offline and discussed that those discrepancies can be dealt with during an actual release PR.

Therefore, this LGTM as a draft that can be merged and sent out to QA

2021-11-18 00:01 UTC, aiyengar2 approved these changes

2021-11-18 00:47 UTC, jiaqiluo approved these changes
LGTM

2021-11-18 00:48 UTC, merged