Bump harvester cloud provider 0.1.6 and csi driver 0.1.7
rancher/charts pull request #1649
Opened 2021-12-10 09:47 UTC by yaocw2020

2021-12-10 11:48 UTC, guangbochen approved these changes

2021-12-10 17:21 UTC, jiaqiluo requested changes
Could you delete the existing `harvester-cloud-provider-100.0.0+up0.1.5` and `harvester-csi-driver-100.0.0+up0.1.6` from the charts/, assets/, and the index.yaml file?  They are replaced by the new versions introduced in this PR so we need to remove them. 

This is a general rule that we should remove the old version when introducing a new version in the dev branch.

2021-12-12 13:49 UTC, yaocw2020 commented
> Could you delete the existing `harvester-cloud-provider-100.0.0+up0.1.5` and `harvester-csi-driver-100.0.0+up0.1.6` from the charts/, assets/, and the index.yaml file? They are replaced by the new versions introduced in this PR so we need to remove them.
> 
> This is a general rule that we should remove the old version when introducing a new version in the dev branch.

I have deleted the old version.

2021-12-13 21:03 UTC, jiaqiluo requested changes

2021-12-13 21:03 UTC, jiaqiluo commented on charts/harvester-cloud-provider/harvester-cloud-provider/100.0.0+up0.1.6/Chart.yaml
> +  catalog.cattle.io/rancher-version: '>= 2.6.1.0 <= 2.6.99-0'
```suggestion
  catalog.cattle.io/rancher-version: '>= 2.6.1-0 <= 2.6.99-0'
```

2021-12-13 21:03 UTC, jiaqiluo commented on charts/harvester-csi-driver/harvester-csi-driver/100.0.0+up0.1.7/Chart.yaml
> +  catalog.cattle.io/rancher-version: '>= 2.6.1.0 <= 2.6.99-0'
```suggestion
  catalog.cattle.io/rancher-version: '>= 2.6.1-0 <= 2.6.99-0'
```

2021-12-13 21:03 UTC, jiaqiluo commented on charts/harvester-csi-driver/harvester-csi-driver/100.0.0+up0.1.7/Chart.yaml
>    catalog.cattle.io/upstream-version: 0.1.6
```suggestion
  catalog.cattle.io/upstream-version: 0.1.7
```

2021-12-13 21:03 UTC, jiaqiluo commented on charts/harvester-cloud-provider/harvester-cloud-provider/100.0.0+up0.1.6/Chart.yaml
>    catalog.cattle.io/upstream-version: 0.1.5
```suggestion
  catalog.cattle.io/upstream-version: 0.1.6
```

2021-12-14 03:00 UTC, jiaqiluo approved these changes

2021-12-14 03:01 UTC, guangbochen commented
@jiaqiluo can u please also help to merge this PR thanks?

2021-12-14 03:08 UTC, merged