Kev2 cluster import fix (integrate changes)
rancher/charts pull request #1725
Opened 2022-02-09 16:00 UTC by annablender

Address https://github.com/rancher/rancher/issues/36128.

Update AKS, EKS, and GKE operator chart versions in rancher/charts

Fixes
* https://github.com/rancher/eks-operator/pull/59
* https://github.com/rancher/aks-operator/pull/52
* https://github.com/rancher/gke-operator/pull/73

2022-02-09 16:07 UTC, kinarashah commented on packages/rancher-aks-operator/rancher-aks-operator-crd/package.yaml
>  url: https://github.com/rancher/aks-operator/releases/download/v1.0.3/rancher-aks-operator-crd-1.0.3.tgz
We'd need to change this to `v1.0.4-rc1`, https://github.com/rancher/charts/pull/1625 for reference.

2022-02-09 16:51 UTC, thedadams requested changes

2022-02-09 16:51 UTC, thedadams commented on packages/rancher-aks-operator/rancher-aks-operator/package.yaml
> +version: 100.0.3
Bumping these versions is correct, but the versions in the above URL also need to be bumped.

Same for all three operators.

2022-02-10 02:01 UTC, thedadams requested changes
Sorry, this part is new and I forgot about it. The new versions of the operators and their CRDs also need to be added to [release.yaml](https://github.com/raulcabello/charts/blob/dev-v2.6/release.yaml).

2022-02-10 21:14 UTC, thedadams submitted a review, later dismissed

2022-02-10 22:58 UTC, thedadams submitted a review, later dismissed

2022-02-11 17:20 UTC, paynejacob approved these changes

2022-02-11 21:33 UTC, annablender commented
Fixed merge conflict. Changes are still the same

2022-02-11 22:01 UTC, paynejacob approved these changes

2022-02-14 20:53 UTC, thedadams requested changes
There is an extra commit in this PR that should be removed.

2022-02-14 21:45 UTC, paynejacob approved these changes

2022-02-14 21:53 UTC, thedadams approved these changes

2022-02-15 14:45 UTC, merged