[2.6] Add istio 1.12.6
rancher/charts pull request #1849
Opened 2022-04-07 16:12 UTC by doflamingo721

Add support for istio 1.12.6:
https://istio.io/latest/news/releases/1.12.x/announcing-1.12.6/

Linked issue:
https://github.com/rancher/rancher/issues/37218

2022-04-11 19:23 UTC, aiyengar2 requested changes
Changes overall look good, but rebase is required and approval is pending the merge of https://github.com/rancher/istio-installer/pull/52 and https://github.com/rancher/image-mirror/pull/231, which have already been approved.

Once approved and rebased, reach out to me for a final review and I can approve this.

2022-04-13 05:22 UTC, doflamingo721 commented
@aiyengar2 I've rebased the PR and the respective image-mirror PR https://github.com/rancher/image-mirror/pull/231 and istio-installer PR https://github.com/rancher/istio-installer/pull/52 have been merged. Can you please review it once?

2022-04-13 16:00 UTC, aiyengar2 commented on packages/rancher-istio/rancher-istio/charts/values.yaml
> +  tag: 1.12.6
https://hub.docker.com/r/rancher/mirrored-istio-pilot/tags?page=1&name=1.12.6

2022-04-13 16:00 UTC, aiyengar2 commented on packages/rancher-istio/rancher-istio/charts/values.yaml
> +    tag: 1.12.6
image exists https://hub.docker.com/r/rancher/mirrored-istio-proxyv2/tags?page=1&name=1.12.6

2022-04-13 16:01 UTC, merged