Gatekeeper: Add node selectors and tolerations for windows
rancher/charts pull request #1872
Opened 2022-04-26 20:09 UTC by eliyamlevy

Issue: https://github.com/rancher/rancher/issues/37029

2022-05-19 15:20 UTC, superseb requested changes
From my limited charts knowledge:

* this seems to change an existing version, while I think it should be a new version with the fix?
* The related issue (https://github.com/rancher/rancher/issues/37029) shows certain jobs being scheduled to windows nodes but I dont see changes in `templates/jobs.yaml`

2022-05-24 19:09 UTC, PennyScissors commented
@superseb you are right about the version. This used to be in a new version, but then it was released in 2.6.5 so the version needs to be bumped again. As for jobs, you are also right. This PR should include this change to add the linux tolerations/node-selectors to the jobs for CRD uninstall https://github.com/rancher/charts/pull/1823/commits/fb996bdae04fec2c3812a6087bcb5fad4f443364

2022-05-26 15:08 UTC, superseb submitted a review, later dismissed

2022-05-26 16:52 UTC, superseb approved these changes

2022-05-26 16:53 UTC, merged