[100.0.0+up1.10.4] Add kube-version annotations to istio 1.10
rancher/charts pull request #1903
Opened 2022-05-17 14:25 UTC by doflamingo721

Linked issue:
https://github.com/rancher/rancher/issues/37697

2022-05-18 03:03 UTC, aiyengar2 requested changes
Currently, this PR is dropping additional changes we added for Windows support.

Also see comment on https://github.com/rancher/charts/pull/1841#discussion_r875425618 about multiple release lines.

2022-05-18 03:03 UTC, aiyengar2 commented on packages/rancher-istio/rancher-tracing/charts/templates/_helpers.tpl
> -
why are we dropping these changes?

2022-05-18 03:03 UTC, aiyengar2 commented on packages/rancher-istio/rancher-tracing/charts/templates/deployment.yaml
> -      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
why are we dropping these changes

2022-05-18 03:03 UTC, aiyengar2 commented on packages/rancher-istio/rancher-tracing/charts/values.yaml
> -## Node labels for pod assignment
why are we dropping these changes?

2022-05-19 07:53 UTC, doflamingo721 commented
Closing this PR in favour of https://github.com/rancher/charts/pull/1905

2022-05-19 07:53 UTC, closed without merging