Add rebase script
rancher/charts pull request #1936
Opened 2022-06-09 21:24 UTC by aiyengar2

This script powered https://github.com/rancher/charts/pull/1072, which rebased 5 charts.

Related Issue: https://github.com/rancher/charts-build-scripts/issues/31

Followup to https://github.com/rancher/charts/pull/1079.

2023-06-22 18:10 UTC, joshmeranda requested changes

2023-06-22 18:10 UTC, joshmeranda commented on scripts/rebase
> +    COMMITS=$(git log --first-parent --oneline ${CURRENT_COMMIT}..${NEW_COMMIT} | cut -d' ' -f1 | tail -r)
suggest replacing ll occurances of  `tail -r` with `tac` as linux GNU `tail` `does not support that option via the [GNU docs](https://www.gnu.org/software/coreutils/manual/html_node/tail-invocation.html#index-BSD-tail)

> GNU tail can output any amount of data (some other versions of tail cannot). It also has no -r option (print in reverse), since reversing a file is really a different job from printing the end of a file; BSD tail (which is the one with -r) can only reverse files that are at most as large as its buffer, which is typically 32 KiB. A more reliable and versatile way to reverse files is the GNU tac command.

@geethub97 @aiyengar2

2024-01-31 18:10 UTC, nicholasSUSE commented
Hello @aiyengar2 can I close this PR?

2024-01-31 18:17 UTC, joshmeranda commented
If we close this issue, I would like to have the rebase script stored somewhere outside of just the prometheus-federator. The rebase script is very helpful, especially when you have to do multiple charts / subcharts so I would like to get this into rancher/charts if possible

2024-01-31 18:36 UTC, recena commented
@joshmeranda You can store the script in your forked repository. In order to improve the traceability and the automation, we plan to set one PR → one chart (modify).

2024-02-01 19:12 UTC, nicholasSUSE commented
> @joshmeranda You can store the script in your forked repository. In order to improve the traceability and the automation, we plan to set one PR → one chart (modify).

This seems promising @recena I will keep this one open. 
Once the efforts for the 2.7.11 and 2.8.1 sync are finished me and @lucasmlp will evaluate it.

2024-05-01 01:11 UTC, joshmeranda commented
Ended up writing a [replacement tool](https://github.com/joshmeranda/chartsutil/tree/main) for this script to get around some of the pain points with the script. If @rancher/mapps is interested, it would be trivial to integrate it into `charts-build-scripts`.

2025-01-30 18:01 UTC, nicholasSUSE commented
Guys I am closing this PR now.

2025-01-30 18:01 UTC, closed without merging