Istio update 1.14.3
rancher/charts pull request #2044
Opened 2022-08-25 12:06 UTC by mitulshah-suse

Related issue https://github.com/rancher/rancher/issues/38451
additional PRs opened 
https://github.com/rancher/image-mirror/pull/275
https://github.com/rancher/istio-installer/pull/59

2022-08-25 12:45 UTC, doflamingo721 commented on packages/rancher-istio/1.14/rancher-kiali-server/generated-changes/patch/templates/deployment.yaml.patch
> ++      {{- end }}
Nit: @mitulshah-suse Can you please remove the whitespaces after `{{- end}}`.

2022-08-25 12:46 UTC, doflamingo721 commented on packages/rancher-istio/1.14/rancher-kiali-server/generated-changes/patch/templates/deployment.yaml.patch
> ++        {{- end }}
Nit: Can you please remove the whitespaces after `{{- end}}`.

2022-08-26 12:06 UTC, doflamingo721 submitted a review, later dismissed
lgtm

2022-09-21 17:57 UTC, aiyengar2 requested changes

2022-09-22 05:53 UTC, mitulshah-suse commented on packages/rancher-istio/1.14/rancher-kiali-server/package.yaml
>  version: 100.0.0
Updated

2022-09-22 05:53 UTC, mitulshah-suse commented on packages/rancher-istio/1.14/rancher-tracing/charts/values.yaml
> +  tag: 1.37.0
Updated

2022-09-22 14:43 UTC, eliyamlevy commented
Merge issues

2022-09-22 17:59 UTC, aiyengar2 submitted a review, later dismissed

2022-09-23 05:52 UTC, doflamingo721 approved these changes

2022-09-23 05:58 UTC, merged