Remove Istio versions prior to 1.14.x
rancher/charts pull request #2119
Opened 2022-09-28 10:34 UTC by rayandas

This PR removes below versions from charts dir:
```
100.3.0+up1.13.3
100.2.1+up1.12.6
100.2.0+up1.12.6
100.1.3+up1.11.8
100.1.2+up1.11.7
100.1.1+up1.11.7
100.1.0+up1.11.4
100.0.2+up1.10.4
100.0.1+up1.10.4
100.0.0+up1.10.4
1.10.400
1.11.700
1.11.701
1.7.100
1.7.300
1.7.301
1.8.300
1.8.500
1.8.600
1.9.300
1.9.500
1.9.600
1.9.800
```
And it removes `1.11` `1.12` and `1.13` from `packages/rancher-istio` dir.

Related: https://github.com/rancher/rancher/issues/39135

2022-09-29 23:11 UTC, prachidamle commented
@aiyengar2 do we need to remove all charts or keep them and just not create the 101 versions of them?

2022-09-29 23:13 UTC, aiyengar2 requested changes
@rayandas all we need is the commit to remove the packages in https://github.com/rancher/charts/pull/2119/commits/85a0ad924527b74fd4b0014e3c29a2a64bd32187. The remaining charts should not be removed since `dev-v2.7` and `release-v2.7` are expected to be strict supersets of `release-v2.6`.

The 2.6 versions of Istio will only be hidden by Rancher annotation from a **fresh** install onto a 2.7 cluster; we still want to allow users to perform in-place upgrades of **existing** installs while they are completing the migration process

2022-09-30 10:24 UTC, rayandas commented
@aiyengar2 Updated the PR with your suggested changes.

2022-10-04 16:37 UTC, aiyengar2 approved these changes

2022-10-05 05:52 UTC, merged