Bump rancher-aks-operator v1.0.7-rc2
rancher/charts pull request #2121
Opened 2022-09-28 18:46 UTC by KevinJoiner

Updates from rc1 to rc2 to include changes for https://github.com/rancher/rancher/issues/37927

2022-09-28 19:55 UTC, cbron approved these changes

2022-09-28 22:13 UTC, cbron requested changes
Branching problems

2022-09-28 22:13 UTC, cbron commented on charts/rancher-aks-operator-crd/101.0.0+up1.0.7-rc2/Chart.yaml
> +appVersion: 1.0.7-rc2
Something weird is going on between 2.6 and 2.7: 
2.6 is at 1.0.7-rc1: https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-aks-operator
But so is 2.7: https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-aks-operator
So I think 1.0.7 needs to be removed from 2.7 and the minor or major version needs to get bumped. 
cc @annablender / @snasovich

2022-09-30 22:21 UTC, cbron approved these changes
I think this is all correct now.

2022-10-03 18:32 UTC, prachidamle approved these changes

2022-10-03 18:36 UTC, merged