Bump rancher-eks-operator v1.1.5-rc2
rancher/charts pull request #2122
Opened 2022-09-28 19:00 UTC by KevinJoiner

Updates from eks-operator rc1 to rc2 to include changes for https://github.com/rancher/rancher/issues/37927

2022-09-28 19:56 UTC, cbron approved these changes

2022-09-28 22:14 UTC, cbron requested changes
Same branching problem as AKS

2022-09-30 22:22 UTC, cbron approved these changes

2022-10-03 18:34 UTC, prachidamle approved these changes

2022-10-03 18:36 UTC, merged