Release longhorn v1.3.2-rc1 into Rancher 2.7
rancher/charts pull request #2133
Opened 2022-10-04 05:50 UTC by PhanLe1010

2022-10-04 05:55 UTC, PhanLe1010 commented on packages/longhorn/longhorn-1.3/generated-changes/patch/Chart.yaml.patch
> ++  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
How do you think @aiyengar2 @innobead @derekbit ?

2022-10-18 12:54 UTC, innobead requested changes
In general, LGTM, but the same question about the exclude in the crd chart. 

Also, suggest consolidate these two commits because there was one for 1.3.2-rc1.

2022-10-18 22:25 UTC, PhanLe1010 commented
> In general, LGTM, but the same question about the exclude in the crd chart.

I responded in the other thread. Thanks 

> Also, suggest consolidate these two commits because there was one for 1.3.2-rc1.

Thank you. Fixed

2022-10-19 05:54 UTC, innobead approved these changes, later dismissed

2022-10-27 21:27 UTC, khushboo-rancher commented
Validated on Rancher 2.7.0-rc7, Installation, uninstallation and some P0 checks are working fine.

2022-10-31 23:00 UTC, khushboo-rancher commented
I verified the upgrade path as below, LGTM.
Longhorn v1.3.1 on Rancher 2.6.9 --> Rancher 2.7.0 --> Longhorn 1.3.2

2022-11-08 19:27 UTC, PhanLe1010 commented
@aiyengar2 @PennyScissors Can we move this one forward?

2022-11-16 19:47 UTC, PennyScissors commented
Please split this into 2 separate commits. First should be changes made packages and release.yaml, and the second should be the output of running make charts.

2022-11-16 19:48 UTC, PennyScissors requested changes
Please split this into 2 separate commits. First should be changes made packages and release.yaml, and the second should be the output of running make charts.

2022-11-17 01:10 UTC, PhanLe1010 commented
> Please split this into 2 separate commits. First should be changes made packages and release.yaml, and the second should be the output of running make charts.

@PennyScissors Done. Thank you

2022-11-17 02:58 UTC, yangchiu commented
Test installallation and uninstallation on rancher v2.7.0: **Pass**

2022-11-17 20:03 UTC, PennyScissors approved these changes

2022-11-17 20:03 UTC, pennyscissors commented on packages/longhorn/longhorn-1.3/generated-changes/patch/Chart.yaml.patch
> ++  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
lgtm

2022-11-17 20:04 UTC, merged