[dev-v2.7] Possible fix for CSI configuration getting omitted while creating RKE2 cluster with vSphere
rancher/charts pull request #2190
Opened 2022-11-02 13:58 UTC by rayandas

Related issue: https://github.com/rancher/rancher/issues/39462
For CPI the version restriction is:
`catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.25.0-0'`
For CSI the version restriction is:
`catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.24.0-0'`

While creating RKE2 cluster, it defaults to K8s 1.24, as the current CSI chart doesn't support for K8s 1.24, that's why the CSI configuration is not visible. This PR changes might fix it.

2022-11-03 20:21 UTC, jiaqiluo commented
@rayandas   
> For CSI the version restriction is:
catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.24.0-0'

This is because the upstream CSI v2.5.1 does not support 1.24. The support is added in upstream CSI v2.6.0 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.6.0

Our CSI chart is maintained at  https://github.com/rancher/vsphere-charts/tree/main/charts/rancher-vsphere-csi.
The good news is that we already update our CSI chart to match the latest version in the upstream which supports 1.24.
So instead of making this PR, we should update the package.yaml to point to a new commit in rancher/vsphere-chart.

2022-11-04 12:49 UTC, rayandas commented
@jiaqiluo Yeah I updated the chart.

2022-11-09 15:00 UTC, annablender requested changes

2022-11-09 15:00 UTC, annablender commented on packages/rancher-vsphere/rancher-vsphere-csi/generated-changes/patch/Chart.yaml.patch
> + appVersion: 2.6.1-rancher1
@brandond recently discovered the appVersion needs to be updated when updates are done to CSI/CPI charts. For CSI, this should be `2.6.2-rancher1.` Could we also update CPI in this PR as well?

2022-11-09 15:00 UTC, annablender commented on release.yaml
> +- 101.1.0+up2.6.1-rancher1
Should be `2.6.2-rancher1`

2022-11-09 15:02 UTC, annablender approved these changes
LGTM. I'm going to put in a PR that will bump CSI to `v2.6.2` as per the current chart changes but this is fine for the UI bug fix

2022-11-09 16:48 UTC, snasovich commented
@annablender , I don't believe we're proceeding with this PR, let's just bump it straight to 2.6.2 or even 2.7.0 that you've introduced in `vsphere-charts` supercharts per https://github.com/rancher/vsphere-charts/pull/35 (more context here - https://github.com/rancher/rancher/issues/39462#issuecomment-1306433102).

2022-11-09 16:48 UTC, closed without merging