Update node-feature-discovery to v0.13.0
rancher/charts pull request #2575
Opened 2023-04-26 07:49 UTC by thomasferrandiz

## Issue: 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations
node-feature-discovery is not installed directly but only as a dependency of the sriov chart.
The installation procedure is described here: 
https://confluence.suse.com/display/RKE2K3S/CNI+Test+Plan?preview=/1120305984/1120305985/how_to_run_sriov(1).txt

For the purpose of testing only nfd, it is enough to install on one machine and check that the node gets labeled by node-feature-discovery.

### Regressions Considerations

## Backporting considerations

2023-04-26 09:35 UTC, rbrtbnfgl submitted a review, later dismissed

2023-06-07 13:24 UTC, manuelbuil approved these changes

2023-06-07 18:12 UTC, rohitsakala approved these changes
LGTM, I wonder if you want to support kube 1.26. 

FYI - The new release of Rancher supports kube 1.26.

2023-06-07 19:05 UTC, diogoasouza commented on packages/rancher-nfd/package.yaml
> +url: https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.13.1/node-feature-discovery-chart-0.13.1.tgz
Shouldn't this be 0.13.2?

2023-06-07 19:07 UTC, rohitsakala requested changes
Please resolve @diogoasouza's comment.

2023-06-08 10:14 UTC, thomasferrandiz commented on packages/rancher-nfd/package.yaml
> +url: https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.13.1/node-feature-discovery-chart-0.13.1.tgz
yes, PR updated.

2023-06-08 10:15 UTC, thomasferrandiz commented
> Please resolve @diogoasouza's comment.

done

2023-06-09 17:36 UTC, diogoasouza approved these changes, later dismissed

2023-06-09 22:31 UTC, rohitsakala submitted a review, later dismissed

2023-06-12 15:36 UTC, rohitsakala approved these changes

2023-06-12 15:39 UTC, diogoasouza approved these changes

2023-06-12 15:48 UTC, merged