Bump vsphere charts k8s 126
rancher/charts pull request #2668
Opened 2023-05-24 14:28 UTC by a-blender

## Issue: 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2023-05-24 17:34 UTC, jiaqiluo requested changes

2023-05-24 17:34 UTC, jiaqiluo commented on packages/rancher-vsphere/rancher-vsphere-cpi/package.yaml
> +version: 103.0.0
We should bump the minor version in the event of adding support for new k8s versions. 

```suggestion
version: 102.1.0
```

2023-05-24 17:34 UTC, jiaqiluo commented on packages/rancher-vsphere/rancher-vsphere-csi/package.yaml
> +version: 103.0.0
We should bump the minor version in the event of adding support for new k8s versions. 
```suggestion
version: 102.1.0
```

2023-05-24 19:30 UTC, jiaqiluo approved these changes

2023-05-24 20:07 UTC, brandond approved these changes

2023-05-24 20:07 UTC, brandond approved these changes

2023-05-24 21:38 UTC, merged

2023-05-24 22:41 UTC, snasovich commented on packages/rancher-vsphere/rancher-vsphere-cpi/generated-changes/patch/Chart.yaml.patch
> ++appVersion: 1.5.1
Just curious, why we need to override this? The "app" is vSphere CPI chart so it makes sense to track the (latest) version of vSphere CPI plugin included.
This was done in `vsphere-charts` superchart recently - https://github.com/rancher/vsphere-charts/pull/55/files#diff-50ddca5e4037a6988a4f9eb12c30c2c5fa8730fb2cc7d07f1517feee49e01804R11

2023-05-25 14:01 UTC, a-blender commented on packages/rancher-vsphere/rancher-vsphere-cpi/generated-changes/patch/Chart.yaml.patch
> ++appVersion: 1.5.1
I was following the pattern of the previous charts https://github.com/rancher/charts/blob/37a92a5927ad61a29bb42558d4ade53a9595a43f/packages/rancher-vsphere/rancher-vsphere-cpi/generated-changes/patch/Chart.yaml.patch#L11-L12 and we override the `appVersion` to match the superchart version.

2023-05-25 14:24 UTC, snasovich commented on packages/rancher-vsphere/rancher-vsphere-cpi/generated-changes/patch/Chart.yaml.patch
> ++appVersion: 1.5.1
@a-blender , got it! Thank you.