Fix ksm/kubelet metricRelabeling issues.
rancher/charts pull request #2725
Opened 2023-06-19 09:35 UTC by hansbogert

## Issue: 
rancher/rancher#43402 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations
Unsure

2023-09-14 08:52 UTC, danielpalstra commented
This PR also addresses issue #2774

2023-10-18 06:10 UTC, staerion commented
This is still a problem for us that seems relatively easy to solve. Could someone please take the time to look at this PR?

2024-02-07 22:42 UTC, nicholasSUSE commented
Hello @hansbogert 
Is this Pull Request still relevant?
Can I close it?

2024-02-08 06:14 UTC, nickvth commented
@nicholasSUSE @hansbogert and I can’t check if this is still relevant, because we stopped(many bugs) with using this chart. Maybe that other people still need this fix like @staerion.

2024-02-14 17:46 UTC, nicholasSUSE commented
> @nicholasSUSE @hansbogert and I can’t check if this is still relevant, because we stopped(many bugs) with using this chart. Maybe that other people still need this fix like @staerion.

Thank you. 
@staerion could you take a look at this?

2024-02-14 21:42 UTC, recena requested changes
This PR is modifying `rancher-kube-state-metrics` but this chart does not exist anymore in [dev-v2.7](https://github.com/rancher/charts/tree/dev-v2.7/packages).

2024-02-14 21:45 UTC, recena commented
I suggest to close this PR.

2024-02-14 21:48 UTC, nicholasSUSE commented
> I suggest to close this PR.

I agree, I will wait for @staerion response before closing it.

2024-02-15 17:43 UTC, alexandreLamarre commented
@recena 

> This PR is modifying `rancher-kube-state-metrics` but this chart does not exist anymore in [dev-v2.7](https://github.com/rancher/charts/tree/dev-v2.7/packages).


@recena @nicholasSUSE rancher-monitoring involves several sub-charts, `kube-state-metrics` is absolutely still an integral part of v2.7, I'd prefer if @joshmeranda and I take over the review of this one, since we are the team managing this line of features

2024-02-15 17:56 UTC, joshmeranda commented
I am going to second @alexandreLamarre here. We are probably better suited for this

2024-02-15 20:13 UTC, nicholasSUSE commented
> I am going to second @alexandreLamarre here. We are probably better suited for this

@alexandreLamarre @joshmeranda thank you for your response.

2024-05-28 09:36 UTC, michisee commented
Is is still broken?

2025-01-30 18:02 UTC, nicholasSUSE commented
I am closing this PR due to lack of activity

2025-01-30 18:02 UTC, closed without merging