Add Longhorn 1.5.1 chart with dev-2.7
rancher/charts pull request #2797
Opened 2023-07-20 02:43 UTC by weizhe0422

[Longhorn 6274](https://github.com/longhorn/longhorn/issues/6274)
[Rancher 42041](https://github.com/rancher/rancher/issues/42041)

Signed-off-by: Ray Chang [ray.chang@suse.com]

cc @innobead @PhanLe1010 @khushboo-rancher @roger-ryao

2023-07-20 03:28 UTC, weizhe0422 commented
Try to install Longhorn `V1.5.1` via Rancher Apps but replace the image repository from rancher mirror: `rancher/mirrored-longhornio-` to `longhornio/, the installation is successful.
![image](https://github.com/rancher/charts/assets/17548901/17dcda11-1d0c-44db-a936-a28a0ac92d1c)
![image](https://github.com/rancher/charts/assets/17548901/b485e8ef-163b-4ecf-8c45-1d74ecd1dc93)

Still need wait QA further verification and mirror images release: https://github.com/rancher/image-mirror/pull/418

@khushboo-rancher @roger-ryao

2023-07-21 00:29 UTC, roger-ryao commented
verify is passed this PR as follow step

**The test steps**
1. Create pod_with_pvc. https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml
2. Create orphaned data.
SSH to one of the nodes and copy the contents of one replica directory, 
e.g., `pvc-abc-…012`, to a new directory named `pvc-abc-…013`. This will make `pvc-abc-…013` an orphaned replica.
3. Deploy a statefulSet and attach to the volume. https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
4. Validate that the volume is created and attached to the pod properly in the Longhorn GUI.
5. Validate the pod is mounted properly.
6. Scale down and up the statefulSet to check volume detach and attach is working fine.

2023-07-21 00:33 UTC, innobead commented
@roger-ryao have you tested the upgrade from the previous rancher chart? https://github.com/longhorn/longhorn/wiki/Release-Test-Plan---1.5.1 cc @khushboo-rancher

2023-07-21 04:59 UTC, roger-ryao commented
> upgrade from the previous rancher chart?

Hi @innobead :
     I haven't tested the upgrade from the previous Rancher chart yet. Let me check it.

2023-07-21 05:17 UTC, innobead commented
Should do the same as you have done at https://github.com/rancher/charts/pull/2780#issuecomment-1644984519.

2023-07-21 09:45 UTC, roger-ryao commented
> Should do the same as you have done at [#2780 (comment)](https://github.com/rancher/charts/pull/2780#issuecomment-1644984519).

- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from v1.4.2 - > v1.5.1
- [x] Upgrade from [v1.4.3](https://github.com/rancher/charts/pull/2780) - > v1.5.1 

**The test steps**
1. Create pod_with_pvc. https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml
2. Create orphaned data.
SSH to one of the nodes and copy the contents of one replica directory, 
e.g., `pvc-abc-…012`, to a new directory named `pvc-abc-…013`. This will make `pvc-abc-…013` an orphaned replica.
3. Deploy a statefulSet and attach to the volume. https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
4. Validate that the volume is created and attached to the pod properly in the Longhorn GUI.
5. Validate the pod is mounted properly.
6. Scale down and up the statefulSet to check volume detach and attach is working fine.

2023-07-26 23:58 UTC, PhanLe1010 requested changes

2023-07-26 23:58 UTC, PhanLe1010 commented on charts/longhorn/102.3.0+up1.5.1/templates/validate-install-crd.yaml
> +# {{- set $found "longhorn.io/v1beta1/Volume" false -}}
Miss the new CRD `volumeattachments.longhorn.io` https://github.com/longhorn/longhorn/blob/19e8fefd3ace7fb66c3f3521fc471b60a829b155/chart/templates/crds.yaml#L3555

2023-07-26 23:58 UTC, PhanLe1010 commented on charts/longhorn/102.3.0+up1.5.1/templates/userroles.yaml
> +              "supportbundles", "supportbundles/status", "systembackups", "systembackups/status", "systemrestores", "systemrestores/status"]
Missing resources "volumeattachments", "volumeattachments/status" https://github.com/longhorn/longhorn/blob/19e8fefd3ace7fb66c3f3521fc471b60a829b155/chart/templates/clusterrole.yaml#L45C15-L45C62

2023-07-26 23:58 UTC, PhanLe1010 commented on charts/longhorn/102.3.0+up1.5.1/templates/userroles.yaml
> +              "supportbundles", "supportbundles/status", "systembackups", "systembackups/status", "systemrestores", "systemrestores/status"]
Missing resources "volumeattachments", "volumeattachments/status" https://github.com/longhorn/longhorn/blob/19e8fefd3ace7fb66c3f3521fc471b60a829b155/chart/templates/clusterrole.yaml#L45C15-L45C62

2023-07-26 23:58 UTC, PhanLe1010 commented on charts/longhorn/102.3.0+up1.5.1/templates/userroles.yaml
> +              "supportbundles", "supportbundles/status", "systembackups", "systembackups/status", "systemrestores", "systemrestores/status"]
Missing resources "volumeattachments", "volumeattachments/status" https://github.com/longhorn/longhorn/blob/19e8fefd3ace7fb66c3f3521fc471b60a829b155/chart/templates/clusterrole.yaml#L45C15-L45C62

2023-07-27 03:18 UTC, weizhe0422 commented
@PhanLe1010 I've update the PR to include the new CRD: `VolumeAttachment`. 

I also refer to [Roger's test steps](https://github.com/rancher/charts/pull/2797#issuecomment-1645310891) to do the upgrade testing from `1.4.2` to `1.5.1`, and doing some tests:
 1. Install `LH 1.4.2` in `Rancher 2.7`
 2. Deploy Pod and related PVC: https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml
 3. Writing some data into the mount point
 4. Upgrade to `LH 1.5.1` in Rancher
 5. Deploy StatefulSet: https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
 6. Make sure all of the workloads works well
    - volumes could attach to the node
    - data is intact after upgrading
    - new workload could be deployed normally
    - Scale down and up the statefulSet to check volume detach and attach is working fine
  
![image](https://github.com/rancher/charts/assets/17548901/bd5af8f7-311c-472f-95cd-077e686430ef)

2023-07-27 18:53 UTC, PhanLe1010 approved these changes
LGTM

2023-07-27 19:02 UTC, rohitsakala submitted a review, later dismissed

2023-07-28 01:32 UTC, rohitsakala commented on index.yaml
> +    version: 102.2.2+up1.4.3
This is a PR for 102.3.0+up1.5.1 but you are adding for 102.2.2+up1.4.3. 

Can you maybe rebase this PR ?

2023-07-28 01:34 UTC, rohitsakala approved these changes, later dismissed

2023-07-28 01:35 UTC, rohitsakala commented on index.yaml
> +    version: 102.2.2+up1.4.3
Outdated Comment.

2023-07-28 04:02 UTC, rohitsakala approved these changes

2023-07-28 04:02 UTC, merged