Update RBAC verbs to include create
rancher/charts pull request #2862
Opened 2023-08-14 23:15 UTC by geethub97

## Issue: <https://github.com/rancher/rancher/issues/40253>

## Problem
Error related to services/proxy when viewing metrics in Rancher UI
## Solution
Add create verb to the services/proxy resource RBAC section 

## Testing
Repro steps in the GH ticket linked above are valid.

2023-08-15 17:58 UTC, joshmeranda approved these changes

2023-08-15 21:44 UTC, prachidamle commented
@aiyengar2 could you please review this RBAC change?

2023-08-28 19:47 UTC, aiyengar2 requested changes

2023-08-28 19:47 UTC, aiyengar2 commented on packages/rancher-monitoring/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/clusterrole.yaml
> +  - 'create'
why do you need endpoints create permissions?

2023-08-28 19:47 UTC, aiyengar2 commented on packages/rancher-monitoring/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/clusterrole.yaml
> +  - 'create'
nit: not sure why some of the stuff in this file uses single quotes and some use no quotes, everything should be standardized (probably no quotes)

2023-08-29 17:19 UTC, geethub97 commented on packages/rancher-monitoring/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/clusterrole.yaml
> +  - 'create'
This was a miss on my part -- have removed this.

2023-08-31 13:26 UTC, aiyengar2 approved these changes

2023-08-31 21:25 UTC, merged