Istio 1.18
rancher/charts pull request #2878
Opened 2023-08-16 22:05 UTC by diogoasouza

2023-08-18 06:15 UTC, rohitsakala requested changes
What about assests and charts directory ?

2023-08-25 17:19 UTC, rohitsakala commented on packages/rancher-istio/1.18/rancher-kiali-server/generated-changes/patch/templates/deployment.yaml.patch
> ++        {{- end }}
Please re check this indentation ?

2023-08-25 20:01 UTC, nicholasSUSE approved these changes

2023-08-25 20:56 UTC, rohitsakala approved these changes

2023-08-25 20:56 UTC, merged