Modifying regsync workflow trigger to protect stored credentials
rancher/charts pull request #3100
Opened 2023-10-04 20:22 UTC by lucasmlp

- Adds latest changes to the task check workflow that are on dev-v2.7;
- Modifies the regsync workflow trigger to protect against malicious PRs;
- Adds check for PR approval before running regsync.

2023-10-04 20:43 UTC, Hypertrophik approved these changes

2023-10-05 04:18 UTC, rohitsakala requested changes

2023-10-05 04:18 UTC, rohitsakala commented on .github/workflows/regsync-config.yaml
> +    if: github.event.label.name == 'regsync-ready' && github.event.pull_request.base.ref == 'release-v2.7'
Can we change this to release-v* ?

2023-10-06 15:10 UTC, rohitsakala approved these changes

2023-10-06 15:10 UTC, merged