Fix typo clsuter to cluster in dev-v2.7 branch
rancher/charts pull request #3107
Opened 2023-10-09 20:27 UTC by reylejano

Fix typo "clsuter" to "cluster" in rancher/charts in the dev-v2.7 branch
Used gsed (macos) `grep -RiIl 'clsuter' | xargs gsed -i 's/clsuter/cluster/g'`

2023-10-09 21:02 UTC, reylejano commented
The proposed change in this PR with the merge conflict is for a typo "clsuter", the conflict in this PR is the fix

2024-02-01 14:43 UTC, recena commented
@rancher/neuvector & @joshmeranda since this PR is modifying your Helm Charts, Do you want to review it and just close it and address it in the upcoming PRs?

2024-02-01 14:49 UTC, joshmeranda commented
I don't see any issues fixing the typos here. I'm ok merging this. But we can close and fix in different PRs, especially since there are no changes to the chart functionality

2024-02-01 14:49 UTC, joshmeranda approved these changes

2024-02-01 14:51 UTC, recena commented
IMO, we shouldn't modify Helm Charts already released.

2024-02-01 14:51 UTC, joshmeranda requested changes
LGTM, just needs conflict resolution

2024-02-01 14:55 UTC, joshmeranda commented
I'd largely agree. For stuff like this where there would be no updates to the actual functionality I think its fine. I'd need to double check but I'm pretty sure it wouldn't benefit anyone to fix the typo in `dev-v2.9` since the charts the typo affects won't work on the k8s versions supported by `dev.v2.9`

2024-02-07 22:43 UTC, nicholasSUSE commented
Hello @reylejano 
Is this Pull Request still relevant?
Can I close it?

2024-02-08 17:55 UTC, selvamt94 commented
@nicholasSUSE @reylejano We will update README in NeuVector upstream chart and update question.yaml in the next NeuVector Rancher chart release.

2024-02-14 23:29 UTC, nicholasSUSE commented
Closing since this fix will be implemented on the upstream chart.

2024-02-14 23:29 UTC, closed without merging