[dev-v2.8] Fixing compatibility issues with build scripts v0.5.3
rancher/charts pull request #3275
Opened 2023-12-18 14:47 UTC by lucasmlp

## Issue: 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2023-12-18 17:02 UTC, rohitsakala requested changes

2023-12-18 17:02 UTC, rohitsakala commented on packages/rancher-monitoring/prometheus-federator/generated-changes/overlay/Chart.yaml.orig
This file shoudnt exist.

2023-12-18 17:02 UTC, rohitsakala commented on packages/rancher-alerting/rancher-alerting-drivers/charts/Chart.yaml
../../charts directory is staging directory. If you run make clean this directory will be removed.

2023-12-18 20:29 UTC, lucasmlp commented on packages/rancher-alerting/rancher-alerting-drivers/charts/Chart.yaml
It's a local chart. It won't be removed by make clean

2023-12-18 20:30 UTC, lucasmlp commented on packages/rancher-monitoring/prometheus-federator/generated-changes/overlay/Chart.yaml.orig
It already exists in the corresponding charts folder. If I remove it, make charts generates a new asset

2023-12-19 14:00 UTC, rohitsuse commented on Makefile
> -	@./scripts/pull-scripts
Why are we removing this ?

2023-12-19 16:19 UTC, joshmeranda commented on packages/rancher-monitoring/prometheus-federator/generated-changes/overlay/Chart.yaml.orig
@lucasmlp @rohitsakala Tested this locally, the file won't get recreate during `make charts`. It would be better for you to remove it if you don't mind

2023-12-19 16:51 UTC, lucasmlp commented on Makefile
> -	@./scripts/pull-scripts
I was testing with the binary. Removing the commit that changed this

2024-01-08 14:07 UTC, closed without merging