[dev-v2.8] Bumping charts-build-scripts version to v0.5.3-rc.1
rancher/charts pull request #3292
Opened 2024-01-02 20:05 UTC by lucasmlp

2024-01-09 11:06 UTC, rohitsakala requested changes

2024-01-09 11:06 UTC, rohitsakala commented on release.yaml
> +  - 103.0..1
Please fix the version

2024-01-09 15:29 UTC, rohitsakala requested changes

2024-01-09 15:29 UTC, rohitsakala commented on assets/prometheus-federator/prometheus-federator-103.0.1+up0.4.1.tgz
We don't need a new version of the chart. we can just edit the chart.yaml.patch for prometheus-federator.

2024-01-09 15:34 UTC, joshmeranda commented on assets/prometheus-federator/prometheus-federator-103.0.1+up0.4.1.tgz
There wasn't a new version of the federator added. `103.0.1+up0.4.1` already existed

2024-01-09 15:37 UTC, joshmeranda commented on packages/rancher-monitoring/prometheus-federator/generated-changes/overlay/Chart.yaml.orig
Do we need this file? Shouldn't really server any purpose

2024-01-09 15:40 UTC, joshmeranda commented on assets/rancher-alerting-drivers/rancher-alerting-drivers-103.0.1.tgz
Do we need a new version for the alerting drivers? If we are just changing how the dependencies are generated / added to chart.yaml, we should just update the `Chart.yaml` and update the current chart if needed.

2024-01-09 17:05 UTC, lucasmlp commented on assets/prometheus-federator/prometheus-federator-103.0.1+up0.4.1.tgz
We can't. Since we already have Chart.yaml.orig into the respective charts folder, it's being generated every time I do a `make prepare` and it has changed. Since it's the original Chart.yaml, it contains the dependencies version. That version of the chart wasn't created by me and it has not been released yet.

2024-01-09 17:07 UTC, lucasmlp commented on assets/rancher-alerting-drivers/rancher-alerting-drivers-103.0.1.tgz
Unfortunatelly, local charts don't have the patch files. Since this new version of the build-scripts adds the dependencies version to Chart.yaml or requirements.yaml, it's mandatory to generate a new chart.

2024-01-09 17:10 UTC, joshmeranda commented on assets/rancher-alerting-drivers/rancher-alerting-drivers-103.0.1.tgz
Ah ok I see. Still not sure I like introducing a new version that doesn't functionally change the chart, but I'd rather track those dependency changes somewhere. Works for me :+1:

2024-01-09 17:16 UTC, lucasmlp commented on assets/prometheus-federator/prometheus-federator-103.0.1+up0.4.1.tgz
The asset is being generated by `make charts` because it's changing the `Chart.yaml.orig` that already exists in the respective charts folder. It isn't being generated because `Chart.yaml` was modified.

2024-01-09 18:39 UTC, joshmeranda approved these changes

2024-01-09 21:53 UTC, diogoasouza commented
Instead of creating a new istio version with just the requirements.yaml chance, can we wait for this https://github.com/rancher/charts/pull/3270 to be merged and add the changes to that version before it's released?

2024-01-10 04:43 UTC, rohitsakala commented
> Instead of creating a new istio version with just the requirements.yaml chance, can we wait for this #3270 to be merged and add the changes to that version before it's released?

Approved PR 3270

2024-01-10 05:07 UTC, rohitsakala commented on assets/prometheus-federator/prometheus-federator-103.0.1+up0.4.1.tgz
@lucasmlp @joshmeranda lets wait for this PR https://github.com/rancher/charts/pull/3300 to get merged and then we can escape creating a new version of prometheus-federator right  ?

2024-01-10 16:45 UTC, lucasmlp commented on assets/prometheus-federator/prometheus-federator-103.0.1+up0.4.1.tgz
@rohitsakala I approved the PR

2024-02-07 15:20 UTC, closed without merging