Add NeuVector chart version 2.7.3 to dev v2.8
rancher/charts pull request #3463
Opened 2024-02-13 03:39 UTC by selvamt94

## Issue: https://github.com/rancher/rancher/issues/44434

## Problem
NeuVector has released app version 5.3.0 along with helm chart 2.7.3, which need to be added to Rancher feature charts version 2.8 (release-v2.8). We would like to get this chart released in the next OOB.

## Solution
new chart has been added

## Testing

## Engineering Testing
### Manual Testing
Tested fresh install of the NeuVector chart 103.0.2+up2.7.3 and upgraded from previous version on RKE and RKE2 cluster.

### Automated Testing

## QA Testing Considerations
Tested fresh install of the NeuVector chart 103.0.2+up2.7.3 and upgraded from previous version on RKE and RKE2 cluster.

### Regressions Considerations

## Backporting considerations

2024-02-14 22:43 UTC, andsont commented
both https://github.com/rancher/charts/pull/3463 and https://github.com/rancher/charts/pull/3464 are reviewed.
all of conditions for image are removed in all deployment yaml files except the registry-adapter.yaml and exporter-deployment.yaml. wondering if u want to make it consistent with other files? if the condition for image is not a concern for rancher chart, it looks good to me.
```
          {{- if .Values.oem }}
          image: "{{ .Values.registry }}/{{ .Values.oem }}/registry-adapter:{{ .Values.cve.adapter.image.tag }}"
          {{- else }}
          image: "{{ .Values.registry }}/registry-adapter:{{ .Values.cve.adapter.image.tag }}"
          {{- end }}
          {{- else }}
          {{- if .Values.cve.adapter.image.hash }}
          image: "{{ .Values.registry }}/{{ .Values.cve.adapter.image.repository }}@{{ .Values.cve.adapter.image.hash }}"
          {{- else }}
          image: {{ template "system_default_registry" . }}{{ .Values.cve.adapter.image.repository }}:{{ .Values.cve.adapter.image.tag }}
          {{- end }}
          {{- end }}
```

2024-02-21 17:29 UTC, lucasmlp approved these changes
LGTM 🚀

2024-02-21 17:52 UTC, lucasmlp requested changes
See release.yaml

2024-02-21 17:52 UTC, lucasmlp commented on release.yaml
> +neuvector:
There is another set of entries for neuvector and neuvector-crd in line 8-10

2024-02-26 16:14 UTC, lucasmlp approved these changes
LGTM 🚀

2024-02-27 19:34 UTC, merged