[dev-v2.8] adding paths filtering code to validation-check
rancher/charts pull request #3497
Opened 2024-02-21 23:47 UTC by nicholasSUSE

Following this PR and improving the solution: https://github.com/rancher/charts/pull/3483

## Problem
Our previous solution created another problem for the `validation-check workflow`. 
Sometimes the validation was required but the previous `validation-comment workflow` was not run because of the filters.

## Solution
Add the same filters for (`assets/ packages/ charts/`) directories to `validation-check workflow`. 
This workflow uses a different type of `github event` so the `paths` directive was not enabled for use. 
The solution implements the same functionality with `javascript` injected code in the workflow.

2024-02-22 21:04 UTC, adamkpickering requested changes

2024-02-22 21:04 UTC, adamkpickering commented on .github/workflows/validation-check.yaml
> +            const latestValidationComment = sortedComments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.sta>
This changes looks like a typo?

2024-02-22 21:04 UTC, adamkpickering commented on .github/workflows/validation-check.yaml
> +            }
Nit: I imagine we want a newline at the end of each file?

2024-03-04 18:11 UTC, nicholasSUSE commented on .github/workflows/validation-check.yaml
> +            }
This makes no difference. 
This is the result of auto-format from VSCode github actions official extension.

2024-03-04 21:14 UTC, adamkpickering approved these changes

2024-03-04 21:18 UTC, merged