make forward-port rancher-istio 102.5.0+up1.19.6 from dev-v2.7.11 to dev-v2.9
rancher/charts pull request #3536
Opened 2024-02-28 19:31 UTC by nicholasSUSE

Synchronizing Istio from dev-v2.7.11 into dev-v2.9 after: https://github.com/rancher/rancher/issues/41840

2024-02-29 19:01 UTC, adamkpickering approved these changes

2024-03-05 20:41 UTC, adamkpickering approved these changes

2024-03-06 14:18 UTC, lucasmlp requested changes
Did you run the `make forward-port` command from `dev-v2.7.11` or `release-v2.7`?

2024-03-06 19:57 UTC, nicholasSUSE commented
Forward ports will be handled all at once, closing this PR

2024-03-06 19:57 UTC, closed without merging