Add rancher istio 1.19.6 dev v2.9
rancher/charts pull request #3538
Opened 2024-02-28 22:40 UTC by nicholasSUSE

## Issue: 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-03-05 20:45 UTC, diogoasouza requested changes
There's a lot of patch files missing inside the rancher-kiali-server folder, is that intentional?

2024-03-05 22:24 UTC, nicholasSUSE commented
> There's a lot of patch files missing inside the rancher-kiali-server folder, is that intentional?

Fixed

2024-03-06 16:19 UTC, lucasmlp approved these changes
LGTM 🚀

Though I would ask @diogoasouza to review it before merging. I'm not able to assess Istio functionality.

2024-03-06 16:19 UTC, lucasmlp commented on packages/rancher-istio/1.19/rancher-istio/charts/Chart.yaml
Is the chart only available with k8s clusters up to 1.27?

2024-03-06 17:15 UTC, nicholasSUSE commented on packages/rancher-istio/1.19/rancher-istio/charts/Chart.yaml
istio Chart version 1.19.6 supports up-to k8s 1.28. 
But Rancher on the official compatibility matrix only supports up-to 1.27.

2024-03-06 17:38 UTC, nicholasSUSE commented on packages/rancher-istio/1.19/rancher-istio/charts/Chart.yaml
@lucasmlp updated the support

2024-03-06 21:09 UTC, diogoasouza approved these changes

2024-03-07 11:57 UTC, merged