[dev-v2.7] Sync-up development branch after Rancher v2.7.11 Charts Release
rancher/charts pull request #3559
Opened 2024-03-05 22:39 UTC by lucasmlp

## Issue: 
https://github.com/rancher/rancher/issues/44273

## Problem

## Solution

git checkout upstream/release-v2.7 -- assets/fleet/fleet-102.2.2+up0.8.2.tgz
git checkout upstream/release-v2.7 -- assets/fleet-agent/fleet-agent-102.2.2+up0.8.2.tgz
git checkout upstream/release-v2.7 -- assets/fleet-crd/fleet-crd-102.2.2+up0.8.2.tgz
git checkout upstream/release-v2.7 -- assets/harvester-cloud-provider/harvester-cloud-provider-102.0.2+up0.2.3.tgz
git checkout upstream/release-v2.7 -- assets/harvester-csi-driver/harvester-csi-driver-102.0.2+up0.1.17.tgz
git checkout upstream/release-v2.7 -- assets/neuvector/neuvector-102.0.8+up2.7.3.tgz
git checkout upstream/release-v2.7 -- assets/neuvector-crd/neuvector-crd-102.0.8+up2.7.3.tgz
git checkout upstream/release-v2.7 -- assets/neuvector-monitor/neuvector-monitor-102.0.8+up2.7.3.tgz
git checkout upstream/release-v2.7 -- assets/rancher-istio/rancher-istio-102.5.0+up1.19.6.tgz
git checkout upstream/release-v2.7 -- assets/rancher-logging/rancher-logging-102.0.2+up3.17.10.tgz
git checkout upstream/release-v2.7 -- assets/rancher-logging-crd/rancher-logging-crd-102.0.2+up3.17.10.tgz
git checkout upstream/release-v2.7 -- charts/harvester-cloud-provider/102.0.2+up0.2.3             
git checkout upstream/release-v2.7 -- charts/rancher-istio/102.5.0+up1.19.6
git checkout upstream/release-v2.7 -- charts/rancher-logging/102.0.2+up3.17.10
git checkout upstream/dev-v2.7 -- packages/rancher-cis-benchmark/
git checkout upstream/release-v2.7 -- packages/harvester/harvester-cloud-provider
git checkout upstream/release-v2.7 -- packages/rancher-backupgit checkout upstream/release-v2.7 -- packages/rancher-istio/1.18/rancher-istio
git checkout upstream/release-v2.7 -- packages/rancher-istio/1.19
rm -rf packages/rancher-monitoring/rancher-monitoring/generated-changes/patch/charts/kube-state-metrics/templates/servicemonitor.yaml.patch
git checkout upstream/release-v2.7 -- packages/rancher-logging/generated-changes/patch/values.yaml.patch
git checkout upstream/release-v2.7 -- assets/rancher-monitoring/rancher-monitoring-102.0.2+up40.1.2.tgz
git checkout upstream/release-v2.7 -- charts/rancher-monitoring/102.0.2+up40.1.2/ 

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-03-06 17:52 UTC, nicholasSUSE approved these changes
LGTM

2024-03-06 18:34 UTC, alexandreLamarre requested changes

2024-03-06 18:34 UTC, alexandreLamarre commented on packages/rancher-logging/generated-changes/patch/values.yaml.patch
The node labels in this file should be `control-plane` as per https://github.com/rancher/charts/pull/3388

2024-03-06 19:19 UTC, lucasmlp commented on packages/rancher-logging/generated-changes/patch/values.yaml.patch
Doing this will cause `make validate` to fail because it'll generate a new `asset`. Since we're talking about a *released chart* I thought that the `package version in `release-v2.7 was the source of truth. Was this change implemented after the `v2.7.11 ' work was done in `rancher-logging 102.0.3+up3.7.10`?

2024-03-07 14:20 UTC, w13915984028 approved these changes
LGTM for Harvester related 2 charts. Thanks.

2024-03-07 14:24 UTC, tomleb approved these changes
LGTM for rancher-webhook

2024-03-07 14:36 UTC, alexandreLamarre approved these changes

2024-03-07 16:02 UTC, mitulshah-suse approved these changes
LGTM from CIS chart perspective

2024-03-07 18:01 UTC, merged