[dev-v2.8] Add rancher-turtles chart
rancher/charts pull request #3594
Opened 2024-03-08 14:59 UTC by salasberryfin

## Issue: 

## Problem

With this change, we're publishing the [rancher-turtles](https://github.com/rancher-sandbox/rancher-turtles) chart to `rancher/charts` for the first time.

## Solution

This just adds the chart and the required references. No other chart should be affected by the change.

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-03-08 15:21 UTC, recena commented
@salasberryfin CODEOWNERS file must be updated.

2024-03-08 15:22 UTC, recena commented
@salasberryfin Instead of `WIP` in the PR title, use the draft GH feature.

2024-03-08 16:47 UTC, nicholasSUSE requested changes

2024-03-08 16:47 UTC, nicholasSUSE commented on packages/rancher-turtles/rancher-turtles/package.yaml
> +version: 100.1.0
Please see the following rules for versioning: https://github.com/rancher/charts/blob/dev-v2.8/README.md#versioning-charts

You are trying to merge at `dev-v2.8` branch.

2024-03-08 16:47 UTC, nicholasSUSE commented on release.yaml
> +- 100.1.0+up0.5.0
Please see the following rules for versioning: https://github.com/rancher/charts/blob/dev-v2.8/README.md#versioning-charts

You are trying to merge at dev-v2.8 branch.

2024-03-08 16:47 UTC, nicholasSUSE commented on charts/rancher-turtles/100.1.0+up0.5.0/Chart.yaml
> +  catalog.cattle.io/rancher-version: '>= 2.7.7-0'
Please se the following Rancher Version Annotations rules at: https://github.com/rancher/charts/blob/dev-v2.8/README.md#rancher-version-annotations

2024-03-08 16:47 UTC, nicholasSUSE commented on charts/rancher-turtles/100.1.0+up0.5.0/Chart.yaml
> +  catalog.cattle.io/kube-version: '>= 1.23.0-0'
Please se the following Rancher Version Annotations rules at: https://github.com/rancher/charts/blob/dev-v2.8/README.md#rancher-version-annotations

2024-03-08 16:47 UTC, nicholasSUSE commented on charts/rancher-turtles/100.1.0+up0.5.0/Chart.lock
> +dependencies:
This chart.lock file is weird, I have not seen this before. 
How was this generated? 
What is it used for?

2024-03-08 16:47 UTC, nicholasSUSE commented on charts/rancher-turtles/100.1.0+up0.5.0/charts/cluster-api-operator/charts/cert-manager/Chart.yaml
> +kubeVersion: '>= 1.22.0-0'
Please se the following Rancher Version Annotations rules at: https://github.com/rancher/charts/blob/dev-v2.8/README.md#rancher-version-annotations

2024-03-08 16:47 UTC, nicholasSUSE commented on charts/rancher-turtles/100.1.0+up0.5.0/Chart.yaml
> +annotations:
For your referenec this is a good example of Chart.yaml on dev-v2.8

https://github.com/rancher/charts/blob/dev-v2.8/charts/rancher-istio/103.2.0%2Bup1.20.3/Chart.yaml

2024-03-08 16:58 UTC, nicholasSUSE commented
@salasberryfin 
Also you need to this process defined here:  https://github.com/rancher/charts/blob/dev-v2.8/README.md#adding-net-new-dependencies-to-dev-27
> When adding new dependencies to dev-2.7, a PR must first be raised and merged in the Rancher repository with the required changes to the pkg/image/origins.go file

If you have this PR ready and merged please attach to the PR description

2024-03-13 15:40 UTC, salasberryfin commented
Closing this as we won't be publishing the chart to `rancher/charts` for now.

2024-03-13 15:40 UTC, closed without merging