[dev-v2.8] Fix versioning on rancher-vsphere-csi chart
rancher/charts pull request #3661
Opened 2024-03-18 19:15 UTC by thatmidwesterncoder

I made a mistake in #3655 where the version was wrong because I bumped the minor version instead of the patch version - this PR just reverts that merge and then creates the correct version of the chart.

2024-03-18 19:33 UTC, jiaqiluo approved these changes

2024-03-18 20:15 UTC, nicholasSUSE approved these changes

2024-03-19 12:41 UTC, lucasmlp requested changes

2024-03-19 12:41 UTC, lucasmlp commented on release.yaml
> -  - 103.2.0+up3.1.2-rancher2
Please, keep only the `rancher-vsphere-csi` version that you're currently working on and the one that should be released in the upcoming _ Rancher v2.8.3_ Release.

2024-03-19 17:48 UTC, nicholasSUSE requested changes

2024-03-19 17:48 UTC, nicholasSUSE commented on index.yaml
> +    digest: eee15afae497390cfe20a56d918ce0a939eba3ae4ade3fdb1115d6e3e2d98152
Conflicts, please resolve

2024-03-19 20:18 UTC, thatmidwesterncoder commented
closing - will fix after 2.8 release.

2024-03-19 20:18 UTC, closed without merging