[dev-v2.9] Fix versioning on rancher-vsphere-csi/cpi chart
rancher/charts pull request #3662
Opened 2024-03-18 19:18 UTC by thatmidwesterncoder

I made a mistake in https://github.com/rancher/charts/pull/3654 where the version was wrong because I bumped the minor version instead of the patch version - this PR just reverts that merge and then creates the correct version of the chart.

edit: also fixed the unpublished versions that were really duplicates since I did it wrong the first few times.

2024-03-18 19:32 UTC, jiaqiluo approved these changes

2024-03-18 20:10 UTC, nicholasSUSE approved these changes

2024-03-19 12:42 UTC, lucasmlp requested changes

2024-03-19 12:42 UTC, lucasmlp commented on release.yaml
> +  - 104.1.1+up3.1.2-rancher2
Please, keep only the `rancher-vsphere-csi` version that you're currently working on and sill be released in the upcoming _ Rancher v2.9.0_ Release.

2024-03-25 18:06 UTC, jakefhyde approved these changes

2024-03-25 19:53 UTC, snasovich approved these changes

2024-03-25 20:03 UTC, thatmidwesterncoder commented
@lucasmlp - updated the PR and had my peers look it over if you'd be down to give it the final :+1:

2024-03-27 12:21 UTC, lucasmlp approved these changes
In future PRs, please update only one chart per PR. this will soon be a requirement for PRs.

2024-03-27 14:23 UTC, merged