[dev-v2.9] fleet 104.0.0+up0.10.0-rc.10 update
rancher/charts pull request #3765
Opened 2024-04-10 15:29 UTC by rancherbot

Update Fleet to v0.10.0-rc.10

Changelog: https://github.com/rancher/fleet/releases/tag/v0.10.0-rc.10

2024-04-10 15:34 UTC, manno approved these changes

2024-04-10 15:36 UTC, thardeck approved these changes

2024-04-11 18:46 UTC, adamkpickering requested changes

2024-04-11 18:46 UTC, adamkpickering commented on index.yaml
> -  - annotations:
I don't think this block deletion has anything to do with this PR?

2024-04-12 04:21 UTC, thardeck commented on index.yaml
> -  - annotations:
It looks like it but the only thing that we run for the commit `Autogenerated changes for Fleet v0.10.0-rc.10`, which changes the `index.yaml`, is removing the previous Fleet 0.10.0-rc.4 charts with `make remove` and then running `PACKAGE=fleet make charts`.

To be sure I also just ran `PACKAGE=fleet make charts` without the removal of the previous Fleet rc version and it still resulted in these annotations being removed.

Running `make validate` is also green.

Do you know anybody who has insight in the `make charts` scripts who can give an insight why this is happening?

2024-04-12 11:35 UTC, thardeck commented
Superseded by #3782

2024-04-12 11:35 UTC, closed without merging

2024-04-12 11:39 UTC, thardeck commented on index.yaml
> -  - annotations:
@adamkpickering https://github.com/rancher/charts/pull/3762/files for example has also the same issue.

Maybe the annotation is not correctly referenced somewhere?