Revert "[dev-v2.7] Bump rancher-vsphere-csi to include a bugfix for CSI Snapshotter (#3658)"
rancher/charts pull request #3766
Opened 2024-04-10 15:32 UTC by thatmidwesterncoder

Reverts https://github.com/rancher/charts/pull/3658, for issue https://github.com/rancher/rancher/issues/43602

This is to prevent breakage due to the 3.1.x version of the chart for the 2.7.x line since it wasn't committed.

2024-04-10 16:35 UTC, snasovich approved these changes

2024-04-10 20:43 UTC, lucasmlp requested changes

2024-04-10 20:43 UTC, lucasmlp commented on release.yaml
> +fleet:
Why is it adding fleet entries?

2024-04-10 21:41 UTC, thatmidwesterncoder commented on release.yaml
> +fleet:
looks like a bad merge on my part. sorry about that!

2024-04-11 13:11 UTC, lucasmlp approved these changes
LGTM 🚀

2024-04-11 18:19 UTC, merged