[dev-v2.9] system-upgrade-controller 104.0.1+up0.7.0 update
rancher/charts pull request #3951
Opened 2024-05-22 08:22 UTC by chiukapoor

## Issue:
* https://github.com/rancher/rancher/issues/44922

## Updates:
* `system-upgrade-controller` is updated to `104.0.1+up0.7.0`
* Removed PSP reference
* Update `rancher_min_version` to `v2.9.0-alpha1`

2024-05-22 18:21 UTC, jiaqiluo requested changes

2024-05-22 18:21 UTC, jiaqiluo commented on packages/system-upgrade-controller/package.yaml
> +version: 104.0.1
We don't need to bump the version of an unreleased chart.

2024-05-23 04:49 UTC, chiukapoor commented on packages/system-upgrade-controller/package.yaml
> +version: 104.0.1
Sure, reverted the version bump.

2024-05-23 16:22 UTC, jiaqiluo approved these changes

2024-05-28 18:40 UTC, jakefhyde approved these changes

2024-05-29 04:55 UTC, merged