Fix patch failures 2.7
rancher/charts pull request #4014
Opened 2024-06-04 19:11 UTC by nicholasSUSE

## Issue: 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-06-04 19:39 UTC, w13915984028 approved these changes
`Harvester-cloud-provider` looks good, thanks.

2024-06-04 20:10 UTC, lucasmlp requested changes

2024-06-04 20:10 UTC, lucasmlp commented on packages/harvester/harvester-cloud-provider/generated-changes/patch/Chart.yaml.patch
> +-  version: 0.4.2
This should be the only change in this file

2024-06-04 20:10 UTC, lucasmlp commented on packages/rancher-monitoring/rancher-project-monitoring/generated-changes/patch/Chart.yaml.patch
> +-  version: 6.38.6
This should be the only change in this file

2024-06-04 20:10 UTC, lucasmlp commented on packages/epinio/epinio/generated-changes/patch/Chart.yaml.patch
> +-  version: 0.14.3
The dependencies version should be the only changes in this file

2024-06-04 20:15 UTC, joshmeranda approved these changes

2024-06-04 20:24 UTC, lucasmlp requested changes
LGTM 🚀

2024-06-04 20:27 UTC, lucasmlp approved these changes
LGTM 🚀

2024-06-05 09:20 UTC, thardeck approved these changes

2024-06-05 23:23 UTC, mgfritch approved these changes
`sriov` chart looks good, thanks!

2024-06-06 00:11 UTC, nicholasSUSE commented on release.yaml
> +rancher-istio:
These versions of rancher-istio and fleet should not be released on the future.
They are just for fixing the patching issues.

2024-06-06 00:24 UTC, merged

2024-06-06 07:18 UTC, andreas-kupries reviewed
lgtm