[dev-v2.9] rancher-vsphere-cpi 104.0.1+up1.8.0 add
rancher/charts pull request #4164
Opened 2024-07-02 05:20 UTC by krunalhinguu

### Updates

- Added new version `104.0.1+up1.8.0` for `rancher-vsphere-cpi` with commit hash `2d84611dada81f4987e67aae58c25a77392c956c`

### Related

- https://github.com/rancher/rancher/issues/45746

2024-07-02 15:56 UTC, snasovich requested changes
The same comment as https://github.com/rancher/charts/pull/4165#pullrequestreview-2154256596 applies (in principle).

2024-07-02 17:37 UTC, krunalhinguu commented
@snasovich I have updated the code. let me if it is correct, i can do the same in another PR

2024-07-03 16:52 UTC, snasovich requested changes
Same comment (in principle) as https://github.com/rancher/charts/pull/4165#pullrequestreview-2156939721 applies

2024-07-03 17:19 UTC, snasovich approved these changes
Approving provided `index.yaml` generation is fixed

2024-07-03 17:34 UTC, merged

2024-07-03 17:50 UTC, jiaqiluo commented on charts/rancher-vsphere-cpi/104.0.0+up1.8.0/Chart.yaml
> +appVersion: 1.30.1
appVersion should be 1.8.0 matching the upstream