[dev-v2.9] Update sriov version to 104.2.0
rancher/charts pull request #4281
Opened 2024-07-22 23:10 UTC by mgfritch

## Issue: 

## Problem

add support for k8s v1.30

## Testing

Deploy charts via helm using a two node RKE2 v1.30.2+rke2r1

2024-07-22 23:17 UTC, nicholasSUSE requested changes
The right version bump is 104.1.1+up0.1.0

2024-07-23 01:52 UTC, nicholasSUSE approved these changes

2024-07-23 02:06 UTC, mgfritch commented
> The right version bump is 104.1.1+up0.1.0

prior major versions of this chart (`102.x`, `103.x`) are bumping the minor version instead of the patch version, let's keep it the same for the `104.x` version series

2024-07-23 14:44 UTC, rbrtbnfgl approved these changes

2024-07-23 15:25 UTC, merged