[2.9.1] Bump vsphere cpi
rancher/charts pull request #4298
Opened 2024-07-29 19:45 UTC by thatmidwesterncoder

## Issue: https://github.com/rancher/rancher/issues/46146 

## Problem

Lots of images showing up rancher-images.txt with security vulnerabilities related to old versions of k8s

## Solution

Bumping rancher-vsphere-cpi in order to remove support for non-supported k8s versions in rancher. 

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-07-29 20:16 UTC, jiaqiluo approved these changes

2024-07-30 17:29 UTC, jiaqiluo requested changes

2024-07-30 17:29 UTC, jiaqiluo commented on charts/rancher-vsphere-cpi/104.0.1+up1.8.1/Chart.yaml
> +  catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.31.0-0'
we need to correct the range.

2024-07-30 20:38 UTC, thatmidwesterncoder commented on charts/rancher-vsphere-cpi/104.0.1+up1.8.1/Chart.yaml
> +  catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.31.0-0'
I have updated the range to exclude invalid k8s versions.

2024-07-30 22:51 UTC, thatmidwesterncoder commented on charts/rancher-vsphere-cpi/104.0.1+up1.8.1/Chart.yaml
> +  catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.31.0-0'
Pulled in changes the correct way!

2024-07-30 23:54 UTC, jiaqiluo approved these changes

2024-07-31 18:27 UTC, HarrisonWAffel approved these changes

2024-08-02 21:34 UTC, merged