Include optional dashboards for logging stack
rancher/charts pull request #4375
Opened 2024-08-22 16:04 UTC by jbiers

## Issue: 
[#46591](https://github.com/rancher/rancher/issues/46591)

## Problem
Implementing two optional Grafana dashboards to monitor the logging stack. Depends on [this already merged PR](https://github.com/rancher/charts/pull/4354).

## Testing
To test this feature a few steps are needed:
- First, it's necessary to enable the metrics.serviceMonitor option in the logging stack for both fluentd and fluentbit as implemented in the mentioned PR.
- Second, enable the loggingMonitoring.fluentd and loggingMonitoring.fluentbit options as implemented in this PR.
- You should now see two new dashboards in Grafana: `Rancher / Fluentd` and `Rancher / Fluentbit`.

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-08-22 16:58 UTC, joshmeranda requested changes

2024-08-22 16:58 UTC, joshmeranda commented on packages/rancher-monitoring/rancher-monitoring/generated-changes/patch/values.yaml.patch
> ++loggingMonitoring:
nit `loggingMonitors`

2024-08-22 17:22 UTC, jbiers commented on packages/rancher-monitoring/rancher-monitoring/generated-changes/patch/values.yaml.patch
> ++loggingMonitoring:
Fixed ;)

2024-08-23 14:24 UTC, joshmeranda approved these changes

2024-08-23 14:35 UTC, merged