[dev-v2.9] racher-monitoring 104.1.2-rc.1+up57.0.3 add
rancher/charts pull request #4451
Opened 2024-09-16 21:15 UTC by ericpromislow

Related to issue [#47092](https://github.com/rancher/rancher/issues/47092)

2024-09-24 17:25 UTC, ericpromislow commented
Note that the actual change is in `packages/rancher-monitoring/rancher-node-exporter/generated-changes/patch/templates/psp-clusterrole.yaml.patch`

2024-09-24 18:07 UTC, joshmeranda requested changes

2024-09-24 18:07 UTC, joshmeranda commented on packages/rancher-monitoring/rancher-monitoring/package.yaml
> +version: 104.1.2-rc.1+up57.0.3
The upstream version is added by `chart-build-scripts` change to `104.1.2-rc.1` thanks!

2024-09-24 20:49 UTC, joshmeranda approved these changes

2024-09-25 15:55 UTC, mallardduck requested changes, later dismissed
Once the `release.yaml` file is updated this is all good to go.

2024-09-25 19:59 UTC, merged