[dev-v2.10] Remove obsolete `sriov` chart
rancher/charts pull request #4698
Opened 2024-11-07 04:58 UTC by mgfritch

## Issue: https://github.com/rancher/rancher/issues/47915

## Problem

Remove the deprecated `sriov` and `node-feature-discovery` charts from the rancher `v2.10` release. 

See also:
* https://github.com/rancher/dashboard/issues/11042
* https://github.com/rancher/charts/pull/4025

2024-11-07 08:25 UTC, thomasferrandiz approved these changes

2024-11-07 11:41 UTC, manuelbuil approved these changes

2025-01-30 22:01 UTC, nicholasSUSE commented
### Warning\n- This pull request has been inactive for more than 30 days.\n- It will be closed if it is not merged until 3 months after creation.

2025-01-30 22:21 UTC, nicholasSUSE requested changes
I cannot remove already released charts. 

If I remove them here, it will break my CI. 
The proper deprecation process is just not to update them anymore.

2026-04-13 18:44 UTC, closed without merging