[dev-v2.10] rancher-cis-benchmark 7.0.0 unrc
rancher/charts pull request #4701
Opened 2024-11-07 14:14 UTC by vardhaman22

## Issue: 

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2024-11-07 15:45 UTC, pjbgf commented on charts/rancher-cis-benchmark-crd/7.0.0/Chart.yaml
> +version: 7.0.0
```suggestion
version: 105.0.0+7.0.0
```

2024-11-07 15:46 UTC, pjbgf commented on charts/rancher-cis-benchmark/7.0.0/Chart.yaml
> +version: 7.0.0
```suggestion
version: 105.0.0+7.0.0
```

2024-11-07 15:47 UTC, pjbgf commented on index.yaml
> +    - assets/rancher-cis-benchmark/rancher-cis-benchmark-7.0.0.tgz
```suggestion
    - assets/rancher-cis-benchmark/rancher-cis-benchmark-105.0.0+7.0.0.tgz
```

2024-11-07 15:47 UTC, pjbgf commented on index.yaml
> +    version: 7.0.0
```suggestion
    version: 105.0.0+7.0.0
```

2024-11-07 15:47 UTC, pjbgf commented on index.yaml
> +    - assets/rancher-cis-benchmark-crd/rancher-cis-benchmark-crd-7.0.0.tgz
```suggestion
    - assets/rancher-cis-benchmark-crd/rancher-cis-benchmark-crd-105.0.0+7.0.0.tgz
```

2024-11-07 15:47 UTC, pjbgf commented on index.yaml
> +    version: 7.0.0
```suggestion
    version: 105.0.0+7.0.0
```

2024-11-07 15:48 UTC, pjbgf commented on packages/rancher-cis-benchmark/charts/Chart.yaml
> +version: 7.0.0
```suggestion
version: 105.0.0+7.0.0
```

2024-11-07 15:48 UTC, pjbgf commented on packages/rancher-cis-benchmark/package.yaml
> +version: 7.0.0
```suggestion
version: 105.0.0+7.0.0
```

2024-11-07 15:48 UTC, pjbgf commented on release.yaml
> +  - 7.0.0
```suggestion
  - 105.0.0+7.0.0
```

2024-11-07 15:48 UTC, pjbgf commented on release.yaml
> +  - 7.0.0
```suggestion
  - 105.0.0+7.0.0
```

2024-11-07 15:49 UTC, pjbgf requested changes
Versioning needs to align with #4685 for this branch.

2024-11-07 15:58 UTC, vardhaman22 commented on charts/rancher-cis-benchmark-crd/7.0.0/Chart.yaml
> +version: 7.0.0
done made it 105.0.0+up7.0.0

2024-11-07 15:58 UTC, vardhaman22 commented on charts/rancher-cis-benchmark/7.0.0/Chart.yaml
> +version: 7.0.0
done

2024-11-07 15:58 UTC, vardhaman22 commented
> Versioning needs to align with #4685 for this branch.

done

2024-11-07 16:06 UTC, pjbgf approved these changes

2024-11-07 16:07 UTC, pjbgf commented
@nicholasSUSE please review this one to make sure it will be compatible with the automation going forward.

2024-11-07 23:15 UTC, nicholasSUSE commented
Please hold on before merging this PR, 
Let's try to execute the proper auto-bump process. 

See: https://github.com/rancher/cis-operator/pull/442

2024-11-11 17:28 UTC, nicholasSUSE commented
Closing in favor of: https://github.com/rancher/charts/pull/4685

2024-11-11 17:28 UTC, closed without merging