prometheus-adapter Nodeselector fix
rancher/charts pull request #4775
Opened 2024-11-21 05:20 UTC by skanakal

## Issue: 

https://github.com/rancher/rancher/issues/48089

## Problem

## Solution

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

### Regressions Considerations

## Backporting considerations

2025-02-03 15:34 UTC, alexandreLamarre requested changes

2025-02-03 15:34 UTC, alexandreLamarre commented on packages/rancher-monitoring/rancher-monitoring/package.yaml
> +version: 105.1.3
We should instead bump these to 105.1.3-rc.1 for testing by QA, otherwise looks good

2025-02-03 15:39 UTC, alexandreLamarre commented
We need to also target dev-v2.11 first for testing I can open this PR 👍

2025-02-04 13:34 UTC, skanakal commented on packages/rancher-monitoring/rancher-monitoring/package.yaml
> +version: 105.1.3
@alexandreLamarre I have changed as per your suggestion...

2025-05-02 20:12 UTC, mallardduck commented
Closing as this was fixed in `105.1.4-rc.1+up61.3.2-rancher.5` via: https://github.com/rancher/rancher/issues/49833

2025-05-02 20:12 UTC, closed without merging