upgraded upstream chart version
rancher/charts pull request #608
Opened 2020-09-03 17:27 UTC by paynejacob

2020-09-03 17:29 UTC, paynejacob commented
https://github.com/rancher/rancher/issues/28682

2020-09-08 18:08 UTC, brendarearden commented
I know that we will only be releasing a single version of the chart for 2.5.0, so deleting the old tgz is good, but did you need to leave it for now for upgrade testing at all?

2020-09-09 23:33 UTC, brendarearden approved these changes
lgtm

2020-09-09 23:40 UTC, prachidamle approved these changes

2020-09-10 18:16 UTC, cbron requested changes

2020-09-10 18:16 UTC, cbron commented on packages/rancher-logging/rancher-logging.patch
> ++description: Helm chart to install Banzai Cloud logging-operator and a cluster logging pipeline.
Goal here is to describe what the chart does not what it is. So like: 
> The Banzai operater collects logs blah blah

2020-09-10 18:16 UTC, cbron commented on packages/rancher-logging/rancher-logging.patch
>   apiVersion: v1
keywords need to be updated

2020-09-10 18:16 UTC, cbron commented on packages/rancher-logging/rancher-logging.patch
>  +  catalog.cattle.io/certified: rancher
Further down the gvr needs to be update to correct format

2020-09-11 20:36 UTC, cbron approved these changes
lgtm, no tgz purge since new version

2020-09-11 20:36 UTC, cbron commented on packages/rancher-logging/rancher-logging.patch
> ++  - security
Not sure what right answer is for keywords, we can fix later.

2020-09-11 21:25 UTC, merged