renamed rke1 to rke
rancher/charts pull request #638
Opened 2020-09-11 21:14 UTC by paynejacob

2020-09-11 21:17 UTC, brendarearden commented
Delete the existing tgz, otherwise it looks good!

2020-09-11 21:27 UTC, brendarearden approved these changes

2020-09-11 23:26 UTC, cbron requested changes
Logging is already moved up to 3.6, so this won't affect 3.4. Either we can leave those affected and not remove tgz's, or update those and remove tgz's. @brendarearden is familiar with backporting changes.

2020-09-16 18:34 UTC, cbron approved these changes
lgtm

2020-09-16 18:36 UTC, merged