Add
rancher/charts pull request #676
Opened 2020-09-21 22:07 UTC by prachidamle

Add system_default_registry for the security-scan and sonobuoy tool images that the operator uses internally https://github.com/rancher/cis-operator/issues/33

2020-09-21 22:15 UTC, cbron requested changes

2020-09-21 22:15 UTC, cbron commented on packages/rancher-cis-benchmark/charts/templates/deployment.yaml
> +          value:{{ template "system_default_registry" . }} {{ .Values.image.sonobuoy.repository }}
```suggestion
          value:{{ template "system_default_registry" . }}{{ .Values.image.sonobuoy.repository }}
```

2020-09-21 22:23 UTC, cbron approved these changes

2020-09-21 22:47 UTC, aiyengar2 approved these changes

2020-09-22 00:53 UTC, PennyScissors approved these changes

2020-09-22 03:59 UTC, merged