Remove backup-restore-operator chart since its renamed
rancher/charts pull request #703
Opened 2020-09-25 21:51 UTC by mrajashree

2020-09-25 22:31 UTC, cbron requested changes
Need to do assets/index.yaml also

2020-09-25 22:39 UTC, cbron commented on assets/index.yaml
> -apiVersion: v1
Just remove the chart, lines 1-39

2020-09-26 00:39 UTC, mrajashree commented on assets/index.yaml
> -apiVersion: v1
ah, my bad

2020-09-27 20:33 UTC, cbron approved these changes

2020-09-27 20:33 UTC, merged