update px version to 2.6
rancher/charts pull request #835
Opened 2020-11-05 21:04 UTC by trierra

2020-11-05 22:33 UTC, harsh-px requested changes

2020-11-05 22:33 UTC, harsh-px commented on charts/portworx/v1.1.1/Chart.yaml
> +    email: tapas@portworx.com
update emails

2020-11-05 22:33 UTC, harsh-px commented on charts/portworx/v1.1.1/values.yaml
> +imageVersion: 2.6                     # Version of the PX Image.
wrong image version. Needs to be 2.6.1.4

2020-11-05 22:33 UTC, harsh-px commented on charts/portworx/v1.1.1/values.yaml
> +storkVersion: 2.4.3
install.portworx.com/2.6 is using Stork 2.5.0

2020-11-05 22:33 UTC, harsh-px commented on charts/portworx/v1.1.1/questions.yml
> +  default: "2.6"
fix stork and px versions in this file too

2021-02-26 18:22 UTC, PennyScissors commented
Hello @trierra @harsh-px, I'm working on cleaning up this repository. Is this issue still relevant? I see that there hasn't been any activity in a while.

2021-05-25 21:14 UTC, harsh-px commented
This can be closed

2021-06-11 22:51 UTC, PennyScissors commented
Closing in favor of https://github.com/rancher/charts/pull/1236

2021-06-11 22:51 UTC, closed without merging